/*
 * graphANNIS
 * Access the graphANNIS corpora and execute AQL queries with this service. 
 *
 * The version of the OpenAPI document: 0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.corpus_tools.annis.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.corpus_tools.annis.api.model.CorpusConfigurationContext;
import org.corpus_tools.annis.api.model.CorpusConfigurationView;
import org.corpus_tools.annis.api.model.ExampleQuery;
import org.corpus_tools.annis.api.model.VisualizerRule;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CorpusConfiguration
 */
public class CorpusConfigurationTest {
    private final CorpusConfiguration model = new CorpusConfiguration();

    /**
     * Model tests for CorpusConfiguration
     */
    @Test
    public void testCorpusConfiguration() {
        // TODO: test CorpusConfiguration
    }

    /**
     * Test the property 'context'
     */
    @Test
    public void contextTest() {
        // TODO: test context
    }

    /**
     * Test the property 'view'
     */
    @Test
    public void viewTest() {
        // TODO: test view
    }

    /**
     * Test the property 'exampleQueries'
     */
    @Test
    public void exampleQueriesTest() {
        // TODO: test exampleQueries
    }

    /**
     * Test the property 'visualizers'
     */
    @Test
    public void visualizersTest() {
        // TODO: test visualizers
    }

}
