/*
 * graphANNIS
 * Access the graphANNIS corpora and execute AQL queries with this service. 
 *
 * The version of the OpenAPI document: 0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.corpus_tools.annis.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for VisualizerRule
 */
public class VisualizerRuleTest {
    private final VisualizerRule model = new VisualizerRule();

    /**
     * Model tests for VisualizerRule
     */
    @Test
    public void testVisualizerRule() {
        // TODO: test VisualizerRule
    }

    /**
     * Test the property 'element'
     */
    @Test
    public void elementTest() {
        // TODO: test element
    }

    /**
     * Test the property 'layer'
     */
    @Test
    public void layerTest() {
        // TODO: test layer
    }

    /**
     * Test the property 'visType'
     */
    @Test
    public void visTypeTest() {
        // TODO: test visType
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'visibility'
     */
    @Test
    public void visibilityTest() {
        // TODO: test visibility
    }

    /**
     * Test the property 'mappings'
     */
    @Test
    public void mappingsTest() {
        // TODO: test mappings
    }

}
