language: java
jdk:
  - openjdk8

env:
  global:
    - MOZ_HEADLESS=1
addons:
  firefox: latest
  
cache:
  directories:
  - $HOME/.m2
  
before_script:
  - export SHORT_VERSION=`echo ${TRAVIS_TAG:-develop} | sed -E 's/(\.[0-9]+)$//'`
  - mkdir -p $HOME/.cargo/bin
  - export PATH=$HOME/.cargo/bin:$TRAVIS_BUILD_DIR/node_modules/.bin/:$PATH
  - misc/download-mdbook.sh 0.4.2
  - misc/download-annis-cli.sh 0.30.0
  # Install geckodriver
  - npm install geckodriver
  # download pcc2 corpus and import it using the CLI
  - wget http://corpus-tools.org/corpora/pcc2_relANNIS.zip
  - mkdir -p  $HOME/.annis/v4/
  - annis -c "import pcc2_relANNIS.zip"  $HOME/.annis/v4/
  
  
script:
  # execute Maven Tests (including integration tests)
  - mvn verify -B
   # generate the documentation for possible deploy
  - mdbook build docs/user-guide/
  - mdbook build docs/developer-guide/
  - mdbook build docs/online-help/

deploy:
  - provider: script
    script: bash $TRAVIS_BUILD_DIR/misc/deploy-docs.sh
    on:
      repo: korpling/ANNIS
      branch: master
      tags: true
      condition: $TRAVIS_OS_NAME = linux
    skip-cleanup: true
  - provider: script
    script: bash $TRAVIS_BUILD_DIR/misc/deploy-docs.sh
    on:
      repo: korpling/ANNIS
      branch: feature/travis-deploy-docs
      condition: $TRAVIS_OS_NAME = linux
    skip-cleanup: true
