language: java
jdk:
  - openjdk8

env:
  global:
    - MOZ_HEADLESS=1
  addons:
    firefox: latest
  
cache:
  directories:
  - $HOME/.m2
  
before_script:
  - export SHORT_VERSION=`echo ${TRAVIS_TAG:-develop} | sed -E 's/(\.[0-9]+)$//'`
  - mkdir -p $HOME/.cargo/bin
  - export PATH=$HOME/.cargo/bin:$PATH
  - misc/download-mdbook.sh 0.3.5
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - tar -xzf geckodriver-v0.26.0-linux64.tar.gz
  - cp geckodriver $HOME/bin/

  
script:
  - mvn test -B
   # generate the documentation for possible deploy
  - mdbook build docs/user-guide/
  - mdbook build docs/developer-guide/
  - mdbook build docs/online-help/
  
deploy:
  - provider: script
    script: bash $TRAVIS_BUILD_DIR/misc/deploy-docs.sh
    on:
      repo: korpling/ANNIS
      branch: master
      tags: true
      condition: $TRAVIS_OS_NAME = linux
    skip-cleanup: true
  - provider: script
    script: bash $TRAVIS_BUILD_DIR/misc/deploy-docs.sh
    on:
      repo: korpling/ANNIS
      branch: feature/travis-deploy-docs
      condition: $TRAVIS_OS_NAME = linux
    skip-cleanup: true