language: java
jdk:
  - openjdk8

env:
  global:
    - MOZ_HEADLESS=1
addons:
  firefox: latest
  
cache:
  directories:
  - $HOME/.m2
  
before_script:
  - export SHORT_VERSION=`echo ${TRAVIS_TAG:-develop} | sed -E 's/(\.[0-9]+)$//'`
  - mkdir -p $HOME/.cargo/bin
  - export PATH=$HOME/.cargo/bin:$TRAVIS_BUILD_DIR/node_modules/.bin/:$PATH
  - misc/download-mdbook.sh 0.4.2
  - misc/download-annis-cli.sh 0.29.2
  # Install Selenium Runner with geckodriver
  - npm install selenium-side-runner
  - npm install geckodriver
  # download pcc2 corpus and import it using the CLI
  - wget http://corpus-tools.org/corpora/pcc2_relANNIS.zip
  - mkdir -p  $HOME/.annis/v4/
  - annis -c "import pcc2_relANNIS.zip"  $HOME/.annis/v4/
  
  
script:
  # execute Maven Tests
  - mvn test -B
   # generate the documentation for possible deploy
  - mdbook build docs/user-guide/
  - mdbook build docs/developer-guide/
  - mdbook build docs/online-help/
  # Compile in desktop mode
  - mvn -Pdesktop package
  # Start in ANNIS in background and in desktop mode, so there is no authentication
  - cd annis-gui/
  - java -jar target/annis-gui-*-desktop.jar --ci &
  - cd ..
  # execute integration tests
  - selenium-side-runner --base-url http://localhost:5712/ -c "browserName=firefox" misc/annis_integration_tests.side

deploy:
  - provider: script
    script: bash $TRAVIS_BUILD_DIR/misc/deploy-docs.sh
    on:
      repo: korpling/ANNIS
      branch: master
      tags: true
      condition: $TRAVIS_OS_NAME = linux
    skip-cleanup: true
  - provider: script
    script: bash $TRAVIS_BUILD_DIR/misc/deploy-docs.sh
    on:
      repo: korpling/ANNIS
      branch: feature/travis-deploy-docs
      condition: $TRAVIS_OS_NAME = linux
    skip-cleanup: true
