language: java
jdk:
  - openjdk8

env:
  global:
    - MOZ_HEADLESS=1
    - TOMCAT_VERSION=8.5.49
  addons:
    firefox: latest
  
cache:
  directories:
  - $HOME/.m2
  
before_script:
  - cd $HOME
  - export SHORT_VERSION=`echo ${TRAVIS_TAG:-develop} | sed -E 's/(\.[0-9]+)$//'`
  - mkdir -p $HOME/.cargo/bin
  - export PATH=$HOME/.cargo/bin:$PATH
  - misc/download-mdbook.sh 0.3.5
  # Install Selenium Runner with geckodriver
  - npm install selenium-side-runner
  - npm install geckodriver
  # download and unzip Tomcat
  - wget http://ftp.fau.de/apache/tomcat/tomcat-8/v$TOMCAT_VERSION/bin/apache-tomcat-$TOMCAT_VERSION.tar.gz
  - tar xvzf apache-tomcat-$TOMCAT_VERSION.tar.gz
  - ls $HOME/*
  # download pcc2 corpus
  - wget http://corpus-tools.org/corpora/pcc2_relANNIS.zip
  - unzip pcc2_relANNIS.zip
  - ls pcc2_v6_relANNIS
  - cd $TRAVIS_BUILD_DIR


  
script:
  # execute Maven Tests
  - mvn test -B
   # generate the documentation for possible deploy
  - mdbook build docs/user-guide/
  - mdbook build docs/developer-guide/
  - mdbook build docs/online-help/
  # import corpora needed for integration tests
  - cd annis-service/target/annis-service-*-distribution/annis-service-*/
  - source bin/setup.sh
  - annis-admin.sh import $HOME/pcc2_v6_relANNIS
  # start needed (web-) services
  - annis-service-no-security.sh start
  - cp $TRAVIS_BUILD_DIR/annis-gui/target/annis-gui.war $HOME/apache-tomcat-$TOMCAT_VERSION/webapps
  - $HOME/apache-tomcat-$TOMCAT_VERSION/bin/startup.sh
  # execute integration tests
  - cd $TRAVIS_BUILD_DIR/
  - selenium-side-runner -c "browserName=firefox" misc/annis_integration_tests.side
  # stop services
  - annis-service-no-security.sh stop
  - $HOME/apache-tomcat-$TOMCAT_VERSION/bin/shutdown.sh
  
deploy:
  - provider: script
    script: bash $TRAVIS_BUILD_DIR/misc/deploy-docs.sh
    on:
      repo: korpling/ANNIS
      branch: master
      tags: true
      condition: $TRAVIS_OS_NAME = linux
    skip-cleanup: true
  - provider: script
    script: bash $TRAVIS_BUILD_DIR/misc/deploy-docs.sh
    on:
      repo: korpling/ANNIS
      branch: feature/travis-deploy-docs
      condition: $TRAVIS_OS_NAME = linux
    skip-cleanup: true