env:
  global:
    - MOZ_HEADLESS=1
addons:
  firefox: latest
  sonarcloud:
    organization: "korpling"
    token:
      secure: "RhDfvqFaw1Uyml2r0rtZeE6WiyiQ6jqU7PVgotmbDG3dNTU5ds3DO6bZNIBrO8Qly2LIkOwi+1DWFWLCyo4KbUVn7jlZqfItk8cg9T1pg6FctEX0SehS8fReo6xI6gXYc+hvzhaztsTpJYpPUB7O3m+9NfG3ts8BeJ8ZqXfrVEo="
  
cache:
  directories:
  - $HOME/.m2

node_js:
  - "10"

branches:
    only:
    - master
    - develop
    - /release/.*/
    - /^v\d+.\d+(.\d+)?(-\S*)?$/

before_script:
  - export SHORT_VERSION=`echo ${TRAVIS_TAG:-develop} | sed -E 's/(\.[0-9]+)$//'`
  - mkdir -p $HOME/.cargo/bin
  - export PATH=$HOME/.cargo/bin:$TRAVIS_BUILD_DIR/node_modules/.bin/:$PATH
  - misc/download-mdbook.sh 0.4.2
  - misc/download-annis-cli.sh 0.30.0
  # Install geckodriver
  - npm install geckodriver
  # download pcc2 corpus and import it using the CLI
  - wget http://corpus-tools.org/corpora/pcc2_relANNIS.zip
  - mkdir -p  $HOME/.annis/v4/
  - annis -c "import pcc2_relANNIS.zip"  $HOME/.annis/v4/
  
  

jobs:
  include:
    - language: java
      jdk: openjdk11
      name: OpenJDK 11 + SonarCloud code analysis
      git:
        depth: false
      script:
         # execute Maven Tests (including integration tests) with enabled code coverage and upload results to SonarCloud
        - mvn -B -Pcoverage verify sonar:sonar -Dsonar.projectKey=korpling_ANNIS
    - language: java
      jdk: openjdk8
      name: OpenJDK 8
      script:
        # execute Maven Tests
        - mvn -B verify
        # generate the documentation for possible deploy
        - mdbook build docs/user-guide/
        - mdbook build docs/developer-guide/
        - mdbook build docs/online-help/
      deploy:
        - provider: script
          script: bash $TRAVIS_BUILD_DIR/misc/deploy-docs.sh
          on:
            repo: korpling/ANNIS
            branch: master
            tags: true
            condition: $TRAVIS_OS_NAME = linux
          skip-cleanup: true
        - provider: script
          script: bash $TRAVIS_BUILD_DIR/misc/deploy-docs.sh
          on:
            repo: korpling/ANNIS
            branch: feature/travis-deploy-docs
            condition: $TRAVIS_OS_NAME = linux
          skip-cleanup: true
