/*
 * graphANNIS
 * Access the graphANNIS corpora and execute AQL queries with this service. 
 *
 * The version of the OpenAPI document: 0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.corpus_tools.annis.api.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Type of component used for linguistic annotations.
 */
@JsonAdapter(AnnotationComponentType.Adapter.class)
public enum AnnotationComponentType {
  
  COVERAGE("Coverage"),
  
  DOMINANCE("Dominance"),
  
  POINTING("Pointing"),
  
  ORDERING("Ordering"),
  
  LEFTTOKEN("LeftToken"),
  
  RIGHTTOKEN("RightToken"),
  
  PARTOF("PartOf");

  private String value;

  AnnotationComponentType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static AnnotationComponentType fromValue(String value) {
    for (AnnotationComponentType b : AnnotationComponentType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<AnnotationComponentType> {
    @Override
    public void write(final JsonWriter jsonWriter, final AnnotationComponentType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public AnnotationComponentType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return AnnotationComponentType.fromValue(value);
    }
  }
}

