/*
 * graphANNIS
 * Access the graphANNIS corpora and execute AQL queries with this service. 
 *
 * The version of the OpenAPI document: 0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.corpus_tools.annis.api.model;

import java.util.Objects;

import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Qualified name for annotation
 */
@ApiModel(description = "Qualified name for annotation")
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-29T10:18:56.988+02:00[Europe/Berlin]")
public class AnnoKey {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_NS = "ns";
  @SerializedName(SERIALIZED_NAME_NS)
  private String ns;


  public AnnoKey name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name of the annotation.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "pos", value = "Name of the annotation.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public AnnoKey ns(String ns) {
    
    this.ns = ns;
    return this;
  }

   /**
   * Namespace of the annotation.
   * @return ns
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "stts", value = "Namespace of the annotation.")

  public String getNs() {
    return ns;
  }


  public void setNs(String ns) {
    this.ns = ns;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AnnoKey annoKey = (AnnoKey) o;
    return Objects.equals(this.name, annoKey.name) &&
        Objects.equals(this.ns, annoKey.ns);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, ns);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnnoKey {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ns: ").append(toIndentedString(ns)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

