/*
 * graphANNIS
 * Access the graphANNIS corpora and execute AQL queries with this service. 
 *
 * The version of the OpenAPI document: 0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.corpus_tools.annis.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Configuration for configuring context in subgraph queries.
 */
@ApiModel(description = "Configuration for configuring context in subgraph queries.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-28T18:59:24.261+02:00[Europe/Berlin]")
public class CorpusConfigurationContext {
  public static final String SERIALIZED_NAME_DEFAULT = "default";
  @SerializedName(SERIALIZED_NAME_DEFAULT)
  private Integer _default;

  public static final String SERIALIZED_NAME_SIZES = "sizes";
  @SerializedName(SERIALIZED_NAME_SIZES)
  private List<Integer> sizes = null;

  public static final String SERIALIZED_NAME_MAX = "max";
  @SerializedName(SERIALIZED_NAME_MAX)
  private Integer max;

  public static final String SERIALIZED_NAME_SEGMENTATION = "segmentation";
  @SerializedName(SERIALIZED_NAME_SEGMENTATION)
  private String segmentation;


  public CorpusConfigurationContext _default(Integer _default) {
    
    this._default = _default;
    return this;
  }

   /**
   * The default context size.
   * @return _default
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The default context size.")

  public Integer getDefault() {
    return _default;
  }


  public void setDefault(Integer _default) {
    this._default = _default;
  }


  public CorpusConfigurationContext sizes(List<Integer> sizes) {
    
    this.sizes = sizes;
    return this;
  }

  public CorpusConfigurationContext addSizesItem(Integer sizesItem) {
    if (this.sizes == null) {
      this.sizes = new ArrayList<Integer>();
    }
    this.sizes.add(sizesItem);
    return this;
  }

   /**
   * Available context sizes to choose from.
   * @return sizes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[1,2,5,10]", value = "Available context sizes to choose from.")

  public List<Integer> getSizes() {
    return sizes;
  }


  public void setSizes(List<Integer> sizes) {
    this.sizes = sizes;
  }


  public CorpusConfigurationContext max(Integer max) {
    
    this.max = max;
    return this;
  }

   /**
   * If set, a maximum context size which should be enforced by the query system.
   * @return max
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "25", value = "If set, a maximum context size which should be enforced by the query system.")

  public Integer getMax() {
    return max;
  }


  public void setMax(Integer max) {
    this.max = max;
  }


  public CorpusConfigurationContext segmentation(String segmentation) {
    
    this.segmentation = segmentation;
    return this;
  }

   /**
   * Default segmentation to use for defining the context, Set to null or omit it if tokens should be used.
   * @return segmentation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "dipl", value = "Default segmentation to use for defining the context, Set to null or omit it if tokens should be used.")

  public String getSegmentation() {
    return segmentation;
  }


  public void setSegmentation(String segmentation) {
    this.segmentation = segmentation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CorpusConfigurationContext corpusConfigurationContext = (CorpusConfigurationContext) o;
    return Objects.equals(this._default, corpusConfigurationContext._default) &&
        Objects.equals(this.sizes, corpusConfigurationContext.sizes) &&
        Objects.equals(this.max, corpusConfigurationContext.max) &&
        Objects.equals(this.segmentation, corpusConfigurationContext.segmentation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_default, sizes, max, segmentation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CorpusConfigurationContext {\n");
    sb.append("    _default: ").append(toIndentedString(_default)).append("\n");
    sb.append("    sizes: ").append(toIndentedString(sizes)).append("\n");
    sb.append("    max: ").append(toIndentedString(max)).append("\n");
    sb.append("    segmentation: ").append(toIndentedString(segmentation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

