/*
 * graphANNIS
 * Access the graphANNIS corpora and execute AQL queries with this service. 
 *
 * The version of the OpenAPI document: 0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.corpus_tools.annis.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Configuration how the results of a query should be shown
 */
@ApiModel(description = "Configuration how the results of a query should be shown")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-28T18:40:46.578+02:00[Europe/Berlin]")
public class CorpusConfigurationView {
  public static final String SERIALIZED_NAME_BASE_TEXT_SEGMENTATION = "base_text_segmentation";
  @SerializedName(SERIALIZED_NAME_BASE_TEXT_SEGMENTATION)
  private String baseTextSegmentation;

  public static final String SERIALIZED_NAME_PAGE_SIZE = "page_size";
  @SerializedName(SERIALIZED_NAME_PAGE_SIZE)
  private Integer pageSize;


  public CorpusConfigurationView baseTextSegmentation(String baseTextSegmentation) {
    
    this.baseTextSegmentation = baseTextSegmentation;
    return this;
  }

   /**
   * Default segmentation to use for the displaying the text, Set to null or omit it if tokens should be used.
   * @return baseTextSegmentation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "dipl", value = "Default segmentation to use for the displaying the text, Set to null or omit it if tokens should be used.")

  public String getBaseTextSegmentation() {
    return baseTextSegmentation;
  }


  public void setBaseTextSegmentation(String baseTextSegmentation) {
    this.baseTextSegmentation = baseTextSegmentation;
  }


  public CorpusConfigurationView pageSize(Integer pageSize) {
    
    this.pageSize = pageSize;
    return this;
  }

   /**
   * Default number of results to show at once for paginated queries.
   * @return pageSize
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "10", value = "Default number of results to show at once for paginated queries.")

  public Integer getPageSize() {
    return pageSize;
  }


  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CorpusConfigurationView corpusConfigurationView = (CorpusConfigurationView) o;
    return Objects.equals(this.baseTextSegmentation, corpusConfigurationView.baseTextSegmentation) &&
        Objects.equals(this.pageSize, corpusConfigurationView.pageSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(baseTextSegmentation, pageSize);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CorpusConfigurationView {\n");
    sb.append("    baseTextSegmentation: ").append(toIndentedString(baseTextSegmentation)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

