/*
 * graphANNIS
 * Access the graphANNIS corpora and execute AQL queries with this service. 
 *
 * The version of the OpenAPI document: 0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.corpus_tools.annis.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Contains the extended results of the count query.
 */
@ApiModel(description = "Contains the extended results of the count query.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-29T10:18:56.988+02:00[Europe/Berlin]")
public class CountExtra {
  public static final String SERIALIZED_NAME_MATCH_COUNT = "match_count";
  @SerializedName(SERIALIZED_NAME_MATCH_COUNT)
  private Integer matchCount;

  public static final String SERIALIZED_NAME_DOCUMENT_COUNT = "document_count";
  @SerializedName(SERIALIZED_NAME_DOCUMENT_COUNT)
  private Integer documentCount;


  public CountExtra matchCount(Integer matchCount) {
    
    this.matchCount = matchCount;
    return this;
  }

   /**
   * Total number of matches.
   * @return matchCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "79017", value = "Total number of matches.")

  public Integer getMatchCount() {
    return matchCount;
  }


  public void setMatchCount(Integer matchCount) {
    this.matchCount = matchCount;
  }


  public CountExtra documentCount(Integer documentCount) {
    
    this.documentCount = documentCount;
    return this;
  }

   /**
   * Number of documents with at least one match.
   * @return documentCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "230", value = "Number of documents with at least one match.")

  public Integer getDocumentCount() {
    return documentCount;
  }


  public void setDocumentCount(Integer documentCount) {
    this.documentCount = documentCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CountExtra countExtra = (CountExtra) o;
    return Objects.equals(this.matchCount, countExtra.matchCount) &&
        Objects.equals(this.documentCount, countExtra.documentCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(matchCount, documentCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CountExtra {\n");
    sb.append("    matchCount: ").append(toIndentedString(matchCount)).append("\n");
    sb.append("    documentCount: ").append(toIndentedString(documentCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

