/*
 * graphANNIS
 * Access the graphANNIS corpora and execute AQL queries with this service. 
 *
 * The version of the OpenAPI document: 0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.corpus_tools.annis.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Description of an attribute of a query.
 */
@ApiModel(description = "Description of an attribute of a query.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-29T10:18:56.988+02:00[Europe/Berlin]")
public class QueryAttributeDescription {
  public static final String SERIALIZED_NAME_ALTERNATIVE = "alternative";
  @SerializedName(SERIALIZED_NAME_ALTERNATIVE)
  private Integer alternative;

  public static final String SERIALIZED_NAME_QUERY_FRAGMENT = "query_fragment";
  @SerializedName(SERIALIZED_NAME_QUERY_FRAGMENT)
  private String queryFragment;

  public static final String SERIALIZED_NAME_VARIABLE = "variable";
  @SerializedName(SERIALIZED_NAME_VARIABLE)
  private String variable;

  public static final String SERIALIZED_NAME_ANNO_NAME = "anno_name";
  @SerializedName(SERIALIZED_NAME_ANNO_NAME)
  private String annoName;


  public QueryAttributeDescription alternative(Integer alternative) {
    
    this.alternative = alternative;
    return this;
  }

   /**
   * ID of the alternative this attribute is part of.
   * @return alternative
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ID of the alternative this attribute is part of.")

  public Integer getAlternative() {
    return alternative;
  }


  public void setAlternative(Integer alternative) {
    this.alternative = alternative;
  }


  public QueryAttributeDescription queryFragment(String queryFragment) {
    
    this.queryFragment = queryFragment;
    return this;
  }

   /**
   * Textual representation of the query fragment for this attribute.
   * @return queryFragment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Textual representation of the query fragment for this attribute.")

  public String getQueryFragment() {
    return queryFragment;
  }


  public void setQueryFragment(String queryFragment) {
    this.queryFragment = queryFragment;
  }


  public QueryAttributeDescription variable(String variable) {
    
    this.variable = variable;
    return this;
  }

   /**
   * Variable name of this attribute.
   * @return variable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Variable name of this attribute.")

  public String getVariable() {
    return variable;
  }


  public void setVariable(String variable) {
    this.variable = variable;
  }


  public QueryAttributeDescription annoName(String annoName) {
    
    this.annoName = annoName;
    return this;
  }

   /**
   * Optional annotation name represented by this attribute.
   * @return annoName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Optional annotation name represented by this attribute.")

  public String getAnnoName() {
    return annoName;
  }


  public void setAnnoName(String annoName) {
    this.annoName = annoName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryAttributeDescription queryAttributeDescription = (QueryAttributeDescription) o;
    return Objects.equals(this.alternative, queryAttributeDescription.alternative) &&
        Objects.equals(this.queryFragment, queryAttributeDescription.queryFragment) &&
        Objects.equals(this.variable, queryAttributeDescription.variable) &&
        Objects.equals(this.annoName, queryAttributeDescription.annoName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(alternative, queryFragment, variable, annoName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryAttributeDescription {\n");
    sb.append("    alternative: ").append(toIndentedString(alternative)).append("\n");
    sb.append("    queryFragment: ").append(toIndentedString(queryFragment)).append("\n");
    sb.append("    variable: ").append(toIndentedString(variable)).append("\n");
    sb.append("    annoName: ").append(toIndentedString(annoName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

