
/*
Copyright (c) 2011 Sencha Inc. - Author: Nicolas Garcia Belmonte (http://philogb.github.com/)

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

 */
 
 (function(){window.$jit=function(a){var a=a||window,b;for(b in $jit)$jit[b].$extend&&(a[b]=$jit[b])};$jit.version="2.0.1";var f=function(a){return document.getElementById(a)};f.empty=function(){};f.extend=function(a,b){for(var c in b||{})a[c]=b[c];return a};f.lambda=function(a){return"function"==typeof a?a:function(){return a}};f.time=Date.now||function(){return+new Date};f.splat=function(a){var b=f.type(a);return b?"array"!=b?[a]:a:[]};f.type=function(a){var b=f.type.s.call(a).match(/^\[object\s(.*)\]$/)[1].toLowerCase();
return"object"!=b?b:a&&a.$$family?a.$$family:a&&a.nodeName&&1==a.nodeType?"element":b};f.type.s=Object.prototype.toString;f.each=function(a,b){if("object"==f.type(a))for(var c in a)b(a[c],c);else{c=0;for(var d=a.length;c<d;c++)b(a[c],c)}};f.indexOf=function(a,b){if(Array.indexOf)return a.indexOf(b);for(var c=0,d=a.length;c<d;c++)if(a[c]===b)return c;return-1};f.map=function(a,b){var c=[];f.each(a,function(a,e){c.push(b(a,e))});return c};f.reduce=function(a,b,c){var d=a.length;if(0==d)return c;for(var e=
3==arguments.length?c:a[--d];d--;)e=b(e,a[d]);return e};f.merge=function(){for(var a={},b=0,c=arguments.length;b<c;b++){var d=arguments[b];if("object"==f.type(d))for(var e in d){var g=d[e],h=a[e];a[e]=h&&"object"==f.type(g)&&"object"==f.type(h)?f.merge(h,g):f.unlink(g)}}return a};f.unlink=function(a){var b;switch(f.type(a)){case "object":b={};for(var c in a)b[c]=f.unlink(a[c]);break;case "array":b=[];c=0;for(var d=a.length;c<d;c++)b[c]=f.unlink(a[c]);break;default:return a}return b};f.zip=function(){if(0===
arguments.length)return[];for(var a=0,b=[],c=arguments.length,d=arguments[0].length;a<d;a++){for(var e=0,g=[];e<c;e++)g.push(arguments[e][a]);b.push(g)}return b};f.rgbToHex=function(a,b){if(3>a.length)return null;if(4==a.length&&0==a[3]&&!b)return"transparent";for(var c=[],d=0;3>d;d++){var e=(a[d]-0).toString(16);c.push(1==e.length?"0"+e:e)}return b?c:"#"+c.join("")};f.hexToRgb=function(a){if(7!=a.length){a=a.match(/^#?(\w{1,2})(\w{1,2})(\w{1,2})$/);a.shift();if(3!=a.length)return null;for(var b=
[],c=0;3>c;c++){var d=a[c];1==d.length&&(d+=d);b.push(parseInt(d,16))}return b}a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]};f.destroy=function(a){f.clean(a);a.parentNode&&a.parentNode.removeChild(a);a.clearAttributes&&a.clearAttributes()};f.clean=function(a){for(var a=a.childNodes,b=0,c=a.length;b<c;b++)f.destroy(a[b])};f.addEvent=function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent("on"+b,c)};f.addEvents=function(a,b){for(var c in b)f.addEvent(a,c,b[c])};f.hasClass=
function(a,b){return-1<(" "+a.className+" ").indexOf(" "+b+" ")};f.addClass=function(a,b){f.hasClass(a,b)||(a.className=a.className+" "+b)};f.removeClass=function(a,b){a.className=a.className.replace(RegExp("(^|\\s)"+b+"(?:\\s|$)"),"$1")};f.getPos=function(a){for(var b=a,c=0,d=0;b&&!/^(?:body|html)$/i.test(b.tagName);)c+=b.offsetLeft,d+=b.offsetTop,b=b.offsetParent;for(var e=b=0;a&&!/^(?:body|html)$/i.test(a.tagName);)b+=a.scrollLeft,e+=a.scrollTop,a=a.parentNode;return{x:c-b,y:d-e}};f.event={get:function(a,
b){b=b||window;return a||b.event},getWheel:function(a){return a.wheelDelta?a.wheelDelta/120:-(a.detail||0)/3},isRightClick:function(a){return 3==a.which||2==a.button},getPos:function(a,b){var b=b||window,a=a||b.event,c=b.document,c=c.documentElement||c.body;a.touches&&a.touches.length&&(a=a.touches[0]);return{x:a.pageX||a.clientX+c.scrollLeft,y:a.pageY||a.clientY+c.scrollTop}},stop:function(a){a.stopPropagation&&a.stopPropagation();a.cancelBubble=!0;a.preventDefault?a.preventDefault():a.returnValue=
!1}};$jit.util=$jit.id=f;var i=function(a){var a=a||{},b=function(){for(var a in this)"function"!=typeof this[a]&&(this[a]=f.unlink(this[a]));this.constructor=b;if(i.prototyping)return this;a=this.initialize?this.initialize.apply(this,arguments):this;this.$$family="class";return a},c;for(c in i.Mutators)a[c]&&(a=i.Mutators[c](a,a[c]),delete a[c]);f.extend(b,this);b.constructor=i;b.prototype=a;return b};i.Mutators={Implements:function(a,b){f.each(f.splat(b),function(b){i.prototyping=b;var b="function"==
typeof b?new b:b,d;for(d in b)d in a||(a[d]=b[d]);delete i.prototyping});return a}};f.extend(i,{inherit:function(a,b){for(var c in b){var d=b[c],e=a[c],g=f.type(d);e&&"function"==g?d!=e&&i.override(a,c,d):a[c]="object"==g?f.merge(e,d):d}return a},override:function(a,b,c){var d=i.prototyping;d&&a[b]!=d[b]&&(d=null);a[b]=function(){var e=this.parent;this.parent=d?d[b]:a[b];var g=c.apply(this,arguments);this.parent=e;return g}}});i.prototype.implement=function(){var a=this.prototype;f.each(Array.prototype.slice.call(arguments||
[]),function(b){i.inherit(a,b)});return this};$jit.Class=i;$jit.json={prune:function(a,b){this.each(a,function(a,d){d==b&&a.children&&(delete a.children,a.children=[])})},getParent:function(a,b){if(a.id==b)return!1;var c=a.children;if(c&&0<c.length)for(var d=0;d<c.length;d++){if(c[d].id==b)return a;var e=this.getParent(c[d],b);if(e)return e}return!1},getSubtree:function(a,b){if(a.id==b)return a;for(var c=0,d=a.children;d&&c<d.length;c++){var e=this.getSubtree(d[c],b);if(null!=e)return e}return null},
eachLevel:function(a,b,c,d){if(b<=c&&(d(a,b),a.children))for(var e=0,a=a.children;e<a.length;e++)this.eachLevel(a[e],b+1,c,d)},each:function(a,b){this.eachLevel(a,0,Number.MAX_VALUE,b)}};$jit.Trans={$extend:!0,linear:function(a){return a}};var z=$jit.Trans,N=function(a,b){b=f.splat(b);return f.extend(a,{easeIn:function(c){return a(c,b)},easeOut:function(c){return 1-a(1-c,b)},easeInOut:function(c){return 0.5>=c?a(2*c,b)/2:(2-a(2*(1-c),b))/2}})};f.each({Pow:function(a,b){return Math.pow(a,b[0]||6)},
Expo:function(a){return Math.pow(2,8*(a-1))},Circ:function(a){return 1-Math.sin(Math.acos(a))},Sine:function(a){return 1-Math.sin((1-a)*Math.PI/2)},Back:function(a,b){b=b[0]||1.618;return Math.pow(a,2)*((b+1)*a-b)},Bounce:function(a){for(var b,c=0,d=1;;c+=d,d/=2)if(a>=(7-4*c)/11){b=d*d-Math.pow((11-6*c-11*a)/4,2);break}return b},Elastic:function(a,b){return Math.pow(2,10*--a)*Math.cos(20*a*Math.PI*(b[0]||1)/3)}},function(a,b){z[b]=N(a)});f.each(["Quad","Cubic","Quart","Quint"],function(a,b){z[a]=
N(function(a){return Math.pow(a,[b+2])})});var C=new i({initialize:function(a){this.setOptions(a)},setOptions:function(a){this.opt=f.merge({duration:2500,fps:40,transition:z.Quart.easeInOut,compute:f.empty,complete:f.empty,link:"ignore"},a||{});return this},step:function(){var a=f.time(),b=this.opt;a<this.time+b.duration?(a=b.transition((a-this.time)/b.duration),b.compute(a)):(this.timer=clearInterval(this.timer),b.compute(1),b.complete())},start:function(){if(!this.check())return this;this.time=
0;this.startTimer();return this},startTimer:function(){var a=this,b=this.opt.fps;if(this.timer)return!1;this.time=f.time()-this.time;this.timer=setInterval(function(){a.step()},Math.round(1E3/b));return!0},pause:function(){this.stopTimer();return this},resume:function(){this.startTimer();return this},stopTimer:function(){if(!this.timer)return!1;this.time=f.time()-this.time;this.timer=clearInterval(this.timer);return!0},check:function(){return!this.timer?!0:"cancel"==this.opt.link?(this.stopTimer(),
!0):!1}}),o=function(){for(var a=arguments,b=0,c=a.length,d={};b<c;b++){var e=o[a[b]];e.$extend?f.extend(d,e):d[a[b]]=e}return d};o.Canvas={$extend:!0,injectInto:"id",type:"2D",width:!1,height:!1,useCanvas:!1,withLabels:!0,background:!1,Scene:{Lighting:{enable:!1,ambient:[1,1,1],directional:{direction:{x:-100,y:-100,z:-100},color:[0.5,0.3,0.1]}}}};o.Tree={$extend:!0,orientation:"left",subtreeOffset:8,siblingOffset:5,indent:10,multitree:!1,align:"center"};o.Node={$extend:!1,overridable:!1,type:"circle",
color:"#ccb",alpha:1,dim:3,height:20,width:90,autoHeight:!1,autoWidth:!1,lineWidth:1,transform:!0,align:"center",angularWidth:1,span:1,CanvasStyles:{}};o.Edge={$extend:!1,overridable:!1,type:"line",color:"#ccb",lineWidth:1,dim:15,alpha:1,epsilon:7,CanvasStyles:{}};o.Fx={$extend:!0,fps:40,duration:2500,transition:$jit.Trans.Quart.easeInOut,clearCanvas:!0};o.Label={$extend:!1,overridable:!1,type:"HTML",style:" ",size:10,family:"sans-serif",textAlign:"center",textBaseline:"alphabetic",color:"#fff"};
o.Tips={$extend:!1,enable:!1,type:"auto",offsetX:20,offsetY:20,force:!1,onShow:f.empty,onHide:f.empty};o.NodeStyles={$extend:!1,enable:!1,type:"auto",stylesHover:!1,stylesClick:!1};o.Events={$extend:!1,enable:!1,enableForEdges:!1,type:"auto",onClick:f.empty,onRightClick:f.empty,onMouseMove:f.empty,onMouseEnter:f.empty,onMouseLeave:f.empty,onDragStart:f.empty,onDragMove:f.empty,onDragCancel:f.empty,onDragEnd:f.empty,onTouchStart:f.empty,onTouchMove:f.empty,onTouchEnd:f.empty,onMouseWheel:f.empty};
o.Navigation={$extend:!1,enable:!1,type:"auto",panning:!1,zooming:!1};o.Controller={$extend:!0,onBeforeCompute:f.empty,onAfterCompute:f.empty,onCreateLabel:f.empty,onPlaceLabel:f.empty,onComplete:f.empty,onBeforePlotLine:f.empty,onAfterPlotLine:f.empty,onBeforePlotNode:f.empty,onAfterPlotNode:f.empty,request:!1};var p={initialize:function(a,b){this.viz=b;this.canvas=b.canvas;this.config=b.config[a];this.nodeTypes=b.fx.nodeTypes;var c=this.config.type;this.labelContainer=(this.dom="auto"==c?"Native"!=
b.config.Label.type:"Native"!=c)&&b.labels.getLabelContainer();this.isEnabled()&&this.initializePost()},initializePost:f.empty,setAsProperty:f.lambda(!1),isEnabled:function(){return this.config.enable},isLabel:function(a,b,c){var a=f.event.get(a,b),b=this.labelContainer,d=a.target||a.srcElement,a=a.relatedTarget;return c?a&&a==this.viz.canvas.getCtx().canvas&&!!d&&this.isDescendantOf(d,b):this.isDescendantOf(d,b)},isDescendantOf:function(a,b){for(;a&&a.parentNode;){if(a.parentNode==b)return a;a=a.parentNode}return!1}},
q={onMouseUp:f.empty,onMouseDown:f.empty,onMouseMove:f.empty,onMouseOver:f.empty,onMouseOut:f.empty,onMouseWheel:f.empty,onTouchStart:f.empty,onTouchMove:f.empty,onTouchEnd:f.empty,onTouchCancel:f.empty},V=new i({initialize:function(a){this.viz=a;this.canvas=a.canvas;this.edge=this.node=!1;this.registeredObjects=[];this.attachEvents()},attachEvents:function(){var a=this.canvas.getElement(),b=this;a.oncontextmenu=f.lambda(!1);f.addEvents(a,{mouseup:function(a,c){var g=f.event.get(a,c);b.handleEvent("MouseUp",
a,c,b.makeEventObject(a,c),f.event.isRightClick(g))},mousedown:function(a,c){var g=f.event.get(a,c);b.handleEvent("MouseDown",a,c,b.makeEventObject(a,c),f.event.isRightClick(g))},mousemove:function(a,c){b.handleEvent("MouseMove",a,c,b.makeEventObject(a,c))},mouseover:function(a,c){b.handleEvent("MouseOver",a,c,b.makeEventObject(a,c))},mouseout:function(a,c){b.handleEvent("MouseOut",a,c,b.makeEventObject(a,c))},touchstart:function(a,c){b.handleEvent("TouchStart",a,c,b.makeEventObject(a,c))},touchmove:function(a,
c){b.handleEvent("TouchMove",a,c,b.makeEventObject(a,c))},touchend:function(a,c){b.handleEvent("TouchEnd",a,c,b.makeEventObject(a,c))}});var c=function(a,c){var g=f.event.get(a,c),g=f.event.getWheel(g);b.handleEvent("MouseWheel",a,c,g)};!document.getBoxObjectFor&&null==window.mozInnerScreenX?f.addEvent(a,"mousewheel",c):a.addEventListener("DOMMouseScroll",c,!1)},register:function(a){this.registeredObjects.push(a)},handleEvent:function(){for(var a=Array.prototype.slice.call(arguments),b=a.shift(),
c=0,d=this.registeredObjects,e=d.length;c<e;c++)d[c]["on"+b].apply(d[c],a)},makeEventObject:function(a,b){var c=this,d=this.viz.graph,e=this.viz.fx,g=e.nodeTypes,h=e.edgeTypes;return{pos:!1,node:!1,edge:!1,contains:!1,getNodeCalled:!1,getEdgeCalled:!1,getPos:function(){var d=c.viz.canvas,e=d.getSize(),g=d.getPos(),h=d.translateOffsetX,E=d.translateOffsetY,s=d.scaleOffsetX,d=d.scaleOffsetY,i=f.event.getPos(a,b);return this.pos={x:1*(i.x-g.x-e.width/2-h)/s,y:1*(i.y-g.y-e.height/2-E)/d}},getNode:function(){if(this.getNodeCalled)return this.node;
this.getNodeCalled=!0;for(var a in d.nodes){var b=d.nodes[a],h=b&&g[b.getData("type")];if(h=h&&h.contains&&h.contains.call(e,b,this.getPos()))return this.contains=h,c.node=this.node=b}return c.node=this.node=!1},getEdge:function(){if(this.getEdgeCalled)return this.edge;this.getEdgeCalled=!0;var a={},b;for(b in d.edges){var g=d.edges[b];a[b]=!0;for(var f in g)if(!(f in a)){var E=g[f],s=E&&h[E.getData("type")];if(s=s&&s.contains&&s.contains.call(e,E,this.getPos()))return this.contains=s,c.edge=this.edge=
E}}return c.edge=this.edge=!1},getContains:function(){if(this.getNodeCalled)return this.contains;this.getNode();return this.contains}}}}),y={initializeExtras:function(){var a=new V(this),b=this;f.each(["NodeStyles","Tips","Navigation","Events"],function(c){var d=new y.Classes[c](c,b);d.isEnabled()&&a.register(d);d.setAsProperty()&&(b[c.toLowerCase()]=d)})},Classes:{}};y.Classes.Events=new i({Implements:[p,q],initializePost:function(){this.fx=this.viz.fx;this.ntypes=this.viz.fx.nodeTypes;this.etypes=
this.viz.fx.edgeTypes;this.moved=this.touchMoved=this.touched=this.pressed=this.hovered=!1},setAsProperty:f.lambda(!0),onMouseUp:function(a,b,c,d){a=f.event.get(a,b);if(!this.moved)if(d)this.config.onRightClick(this.hovered,c,a);else this.config.onClick(this.pressed,c,a);if(this.pressed){if(this.moved)this.config.onDragEnd(this.pressed,c,a);else this.config.onDragCancel(this.pressed,c,a);this.pressed=this.moved=!1}},onMouseOut:function(a,b,c){var d=f.event.get(a,b),e;if(this.dom&&(e=this.isLabel(a,
b,!0)))this.config.onMouseLeave(this.viz.graph.getNode(e.id),c,d),this.hovered=!1;else{a=d.relatedTarget;for(b=this.canvas.getElement();a&&a.parentNode;){if(b==a.parentNode)return;a=a.parentNode}this.hovered&&(this.config.onMouseLeave(this.hovered,c,d),this.hovered=!1)}},onMouseOver:function(a,b,c){var d=f.event.get(a,b),e;if(this.dom&&(e=this.isLabel(a,b,!0)))this.hovered=this.viz.graph.getNode(e.id),this.config.onMouseEnter(this.hovered,c,d)},onMouseMove:function(a,b,c){a=f.event.get(a,b);if(this.pressed)this.moved=
!0,this.config.onDragMove(this.pressed,c,a);else if(this.dom)this.config.onMouseMove(this.hovered,c,a);else{if(this.hovered){var b=this.hovered,d=b.nodeFrom?this.etypes[b.getData("type")]:this.ntypes[b.getData("type")];if(d&&d.contains&&d.contains.call(this.fx,b,c.getPos())){this.config.onMouseMove(b,c,a);return}this.config.onMouseLeave(b,c,a);this.hovered=!1}if(this.hovered=c.getNode()||this.config.enableForEdges&&c.getEdge())this.config.onMouseEnter(this.hovered,c,a);else this.config.onMouseMove(!1,
c,a)}},onMouseWheel:function(a,b,c){this.config.onMouseWheel(c,f.event.get(a,b))},onMouseDown:function(a,b,c){var d=f.event.get(a,b);if(this.dom){if(a=this.isLabel(a,b))this.pressed=this.viz.graph.getNode(a.id)}else this.pressed=c.getNode()||this.config.enableForEdges&&c.getEdge();this.pressed&&this.config.onDragStart(this.pressed,c,d)},onTouchStart:function(a,b,c){var d=f.event.get(a,b),e;(this.touched=this.dom&&(e=this.isLabel(a,b))?this.viz.graph.getNode(e.id):c.getNode()||this.config.enableForEdges&&
c.getEdge())&&this.config.onTouchStart(this.touched,c,d)},onTouchMove:function(a,b,c){a=f.event.get(a,b);this.touched&&(this.touchMoved=!0,this.config.onTouchMove(this.touched,c,a))},onTouchEnd:function(a,b,c){a=f.event.get(a,b);if(this.touched){if(this.touchMoved)this.config.onTouchEnd(this.touched,c,a);else this.config.onTouchCancel(this.touched,c,a);this.touched=this.touchMoved=!1}}});y.Classes.Tips=new i({Implements:[p,q],initializePost:function(){if(document.body){var a=f("_tooltip")||document.createElement("div");
a.id="_tooltip";a.className="tip";f.extend(a.style,{position:"absolute",display:"none",zIndex:13E3});document.body.appendChild(a);this.tip=a;this.node=!1}},setAsProperty:f.lambda(!0),onMouseOut:function(a,b){f.event.get(a,b);if(this.dom&&this.isLabel(a,b,!0))this.hide(!0);else{for(var c=a.relatedTarget,d=this.canvas.getElement();c&&c.parentNode;){if(d==c.parentNode)return;c=c.parentNode}this.hide(!1)}},onMouseOver:function(a,b){var c;if(this.dom&&(c=this.isLabel(a,b,!1)))this.node=this.viz.graph.getNode(c.id),
this.config.onShow(this.tip,this.node,c)},onMouseMove:function(a,b,c){this.dom&&this.isLabel(a,b)&&this.setTooltipPosition(f.event.getPos(a,b));if(!this.dom){var d=c.getNode();if(d){if(this.config.force||!this.node||this.node.id!=d.id)this.node=d,this.config.onShow(this.tip,d,c.getContains());this.setTooltipPosition(f.event.getPos(a,b))}else this.hide(!0)}},setTooltipPosition:function(a){var b=this.tip,c=b.style,d=this.config;c.display="";var e=document.body.clientWidth,g=b.offsetWidth,b=b.offsetHeight,
h=d.offsetX,d=d.offsetY;c.top=(a.y+d+b>document.body.clientHeight?a.y-b-d:a.y+d)+"px";c.left=(a.x+g+h>e?a.x-g-h:a.x+h)+"px"},hide:function(a){this.tip.style.display="none";a&&this.config.onHide()}});y.Classes.NodeStyles=new i({Implements:[p,q],initializePost:function(){this.fx=this.viz.fx;this.types=this.viz.fx.nodeTypes;this.nStyles=this.config;this.nodeStylesOnHover=this.nStyles.stylesHover;this.nodeStylesOnClick=this.nStyles.stylesClick;this.hoveredNode=!1;this.fx.nodeFxAnimation=new C;this.move=
this.down=!1},onMouseOut:function(a,b){this.down=this.move=!1;if(this.hoveredNode){this.dom&&this.isLabel(a,b,!0)&&this.toggleStylesOnHover(this.hoveredNode,!1);for(var c=a.relatedTarget,d=this.canvas.getElement();c&&c.parentNode;){if(d==c.parentNode)return;c=c.parentNode}this.toggleStylesOnHover(this.hoveredNode,!1);this.hoveredNode=!1}},onMouseOver:function(a,b){var c;if(this.dom&&(c=this.isLabel(a,b,!0)))c=this.viz.graph.getNode(c.id),c.selected||(this.hoveredNode=c,this.toggleStylesOnHover(this.hoveredNode,
!0))},onMouseDown:function(a,b,c,d){if(!d){var e;this.dom&&(e=this.isLabel(a,b))?this.down=this.viz.graph.getNode(e.id):this.dom||(this.down=c.getNode());this.move=!1}},onMouseUp:function(a,b,c,d){if(!d){if(!this.move)this.onClick(c.getNode());this.down=this.move=!1}},getRestoredStyles:function(a,b){var c={},d=this["nodeStylesOn"+b],e;for(e in d)c[e]=a.styles["$"+e];return c},toggleStylesOnHover:function(a,b){this.nodeStylesOnHover&&this.toggleStylesOn("Hover",a,b)},toggleStylesOnClick:function(a,
b){this.nodeStylesOnClick&&this.toggleStylesOn("Click",a,b)},toggleStylesOn:function(a,b,c){var d=this.viz;if(c){b.styles||(b.styles=f.merge(b.data,{}));for(var e in this["nodeStylesOn"+a])c="$"+e,c in b.styles||(b.styles[c]=b.getData(e));d.fx.nodeFx(f.extend({elements:{id:b.id,properties:this["nodeStylesOn"+a]},transition:z.Quart.easeOut,duration:300,fps:40},this.config))}else a=this.getRestoredStyles(b,a),d.fx.nodeFx(f.extend({elements:{id:b.id,properties:a},transition:z.Quart.easeOut,duration:300,
fps:40},this.config))},onClick:function(a){if(a){var b=this.nodeStylesOnClick;b&&(a.selected?(this.toggleStylesOnClick(a,!1),delete a.selected):(this.viz.graph.eachNode(function(a){if(a.selected){for(var d in b)a.setData(d,a.styles["$"+d],"end");delete a.selected}}),this.toggleStylesOnClick(a,!0),a.selected=!0,delete a.hovered,this.hoveredNode=!1))}},onMouseMove:function(a,b,c){this.down&&(this.move=!0);if(!this.dom||!this.isLabel(a,b)){var d=this.nodeStylesOnHover;if(d&&!this.dom){if(this.hoveredNode&&
(a=this.types[this.hoveredNode.getData("type")])&&a.contains&&a.contains.call(this.fx,this.hoveredNode,c.getPos()))return;c=c.getNode();if((this.hoveredNode||c)&&!c.hovered)c&&!c.selected?(this.fx.nodeFxAnimation.stopTimer(),this.viz.graph.eachNode(function(a){if(a.hovered&&!a.selected){for(var b in d)a.setData(b,a.styles["$"+b],"end");delete a.hovered}}),c.hovered=!0,this.hoveredNode=c,this.toggleStylesOnHover(c,!0)):this.hoveredNode&&!this.hoveredNode.selected&&(this.fx.nodeFxAnimation.stopTimer(),
this.toggleStylesOnHover(this.hoveredNode,!1),delete this.hoveredNode.hovered,this.hoveredNode=!1)}}}});y.Classes.Navigation=new i({Implements:[p,q],initializePost:function(){this.pressed=this.pos=!1},onMouseWheel:function(a,b,c){this.config.zooming&&(f.event.stop(f.event.get(a,b)),a=1+c*(this.config.zooming/1E3),this.canvas.scale(a,a))},onMouseDown:function(a,b,c){if(this.config.panning&&!("avoid nodes"==this.config.panning&&(this.dom?this.isLabel(a,b):c.getNode()))){this.pressed=!0;this.pos=c.getPos();
var a=this.canvas,b=a.translateOffsetX,c=a.translateOffsetY,d=a.scaleOffsetY;this.pos.x*=a.scaleOffsetX;this.pos.x+=b;this.pos.y*=d;this.pos.y+=c}},onMouseMove:function(a,b,c){if(this.config.panning&&this.pressed&&!("avoid nodes"==this.config.panning&&(this.dom?this.isLabel(a,b):c.getNode()))){var a=this.pos,c=c.getPos(),d=this.canvas,e=d.translateOffsetX,g=d.translateOffsetY,b=d.scaleOffsetX,d=d.scaleOffsetY;c.x*=b;c.y*=d;c.x+=e;c.y+=g;e=c.x-a.x;a=c.y-a.y;this.pos=c;this.canvas.translate(1*e/b,1*
a/d)}},onMouseUp:function(){this.config.panning&&(this.pressed=!1)}});var u,F=function(a,b){var c=document.createElement(a),d;for(d in b)"object"==typeof b[d]?f.extend(c[d],b[d]):c[d]=b[d];"canvas"==a&&(!P&&G_vmlCanvasManager)&&(c=G_vmlCanvasManager.initElement(document.body.appendChild(c)));return c},p=typeof HTMLCanvasElement,P="object"==p||"function"==p;$jit.Canvas=u=new i({canvases:[],pos:!1,element:!1,labelContainer:!1,translateOffsetX:0,translateOffsetY:0,scaleOffsetX:1,scaleOffsetY:1,initialize:function(a,
b){this.viz=a;this.opt=this.config=b;var c="string"==f.type(b.injectInto)?b.injectInto:b.injectInto.id,d=b.type,e=c+"-label",g=f(c),h=b.width||g.offsetWidth,j=b.height||g.offsetHeight;this.id=c;var k={injectInto:c,width:h,height:j};this.element=F("div",{id:c+"-canvaswidget",style:{position:"relative",width:h+"px",height:j+"px"}});this.labelContainer=this.createLabelContainer(b.Label.type,e,k);this.canvases.push(new u.Base[d]({config:f.extend({idSuffix:"-canvas"},k),plot:function(){a.fx.plot()},resize:function(){a.refresh()}}));
if(c=b.background)k=new u.Background[c.type](a,f.extend(c,k)),this.canvases.push(new u.Base[d](k));for(d=this.canvases.length;d--;)this.element.appendChild(this.canvases[d].canvas),0<d&&this.canvases[d].plot();this.element.appendChild(this.labelContainer);g.appendChild(this.element);var m=null,D=this;f.addEvent(window,"scroll",function(){clearTimeout(m);m=setTimeout(function(){D.getPos(!0)},500)})},getCtx:function(a){return this.canvases[a||0].getCtx()},getConfig:function(){return this.opt},getElement:function(){return this.element},
getSize:function(a){return this.canvases[a||0].getSize()},resize:function(a,b){this.getPos(!0);this.translateOffsetX=this.translateOffsetY=0;this.scaleOffsetX=this.scaleOffsetY=1;for(var c=0,d=this.canvases.length;c<d;c++)this.canvases[c].resize(a,b);c=this.element.style;c.width=a+"px";c.height=b+"px";this.labelContainer&&(this.labelContainer.style.width=a+"px")},translate:function(a,b,c){this.translateOffsetX+=a*this.scaleOffsetX;this.translateOffsetY+=b*this.scaleOffsetY;for(var d=0,e=this.canvases.length;d<
e;d++)this.canvases[d].translate(a,b,c)},scale:function(a,b){var c=this.scaleOffsetX*a,d=this.scaleOffsetY*b,e=this.translateOffsetX*(a-1)/c,g=this.translateOffsetY*(b-1)/d;this.scaleOffsetX=c;this.scaleOffsetY=d;c=0;for(d=this.canvases.length;c<d;c++)this.canvases[c].scale(a,b,!0);this.translate(e,g,!1)},getPos:function(a){return a||!this.pos?this.pos=f.getPos(this.getElement()):this.pos},clear:function(a){this.canvases[a||0].clear()},path:function(a,b){var c=this.canvases[0].getCtx();c.beginPath();
b(c);c[a]();c.closePath()},createLabelContainer:function(a,b,c){if("HTML"==a||"Native"==a)return F("div",{id:b,style:{overflow:"visible",position:"absolute",top:0,left:0,width:c.width+"px",height:0}});if("SVG"==a){a=document.createElementNS("http://www.w3.org/2000/svg","svg:svg");a.setAttribute("width",c.width);a.setAttribute("height",c.height);var d=a.style;d.position="absolute";d.left=d.top="0px";d=document.createElementNS("http://www.w3.org/2000/svg","svg:g");d.setAttribute("width",c.width);d.setAttribute("height",
c.height);d.setAttribute("x",0);d.setAttribute("y",0);d.setAttribute("id",b);a.appendChild(d);return a}}});u.Base={};u.Base["2D"]=new i({translateOffsetX:0,translateOffsetY:0,scaleOffsetX:1,scaleOffsetY:1,initialize:function(a){this.viz=a;this.opt=a.config;this.size=!1;this.createCanvas();this.translateToCenter()},createCanvas:function(){var a=this.opt,b=a.width,c=a.height;this.canvas=F("canvas",{id:a.injectInto+a.idSuffix,width:b,height:c,style:{position:"absolute",top:0,left:0,width:b+"px",height:c+
"px"}})},getCtx:function(){return!this.ctx?this.ctx=this.canvas.getContext("2d"):this.ctx},getSize:function(){if(this.size)return this.size;var a=this.canvas;return this.size={width:a.width,height:a.height}},translateToCenter:function(a){var b=this.getSize(),c=a?b.width-a.width-2*this.translateOffsetX:b.width;height=a?b.height-a.height-2*this.translateOffsetY:b.height;b=this.getCtx();a&&b.scale(1/this.scaleOffsetX,1/this.scaleOffsetY);b.translate(c/2,height/2)},resize:function(a,b){var c=this.getSize(),
d=this.canvas,e=d.style;this.size=!1;d.width=a;d.height=b;e.width=a+"px";e.height=b+"px";P?this.translateToCenter():this.translateToCenter(c);this.translateOffsetX=this.translateOffsetY=0;this.scaleOffsetX=this.scaleOffsetY=1;this.clear();this.viz.resize(a,b,this)},translate:function(a,b,c){var d=this.scaleOffsetY;this.translateOffsetX+=a*this.scaleOffsetX;this.translateOffsetY+=b*d;this.getCtx().translate(a,b);!c&&this.plot()},scale:function(a,b,c){this.scaleOffsetX*=a;this.scaleOffsetY*=b;this.getCtx().scale(a,
b);!c&&this.plot()},clear:function(){var a=this.getSize(),b=this.translateOffsetX,c=this.translateOffsetY,d=this.scaleOffsetX,e=this.scaleOffsetY;this.getCtx().clearRect(1*(-a.width/2-b)/d,1*(-a.height/2-c)/e,1*a.width/d,1*a.height/e)},plot:function(){this.clear();this.viz.plot(this)}});u.Background={};u.Background.Circles=new i({initialize:function(a,b){this.viz=a;this.config=f.merge({idSuffix:"-bkcanvas",levelDistance:100,numberOfCircles:6,CanvasStyles:{},offset:0},b)},resize:function(a,b,c){this.plot(c)},
plot:function(a){var a=a.getCtx(),b=this.config,c=b.CanvasStyles,d;for(d in c)a[d]=c[d];d=b.numberOfCircles;b=b.levelDistance;for(c=1;c<=d;c++)a.beginPath(),a.arc(0,0,b*c,0,2*Math.PI,!1),a.stroke(),a.closePath()}});var t=function(a,b){this.theta=a||0;this.rho=b||0};$jit.Polar=t;t.prototype={getc:function(a){return this.toComplex(a)},getp:function(){return this},set:function(a){a=a.getp();this.theta=a.theta;this.rho=a.rho},setc:function(a,b){this.rho=Math.sqrt(a*a+b*b);this.theta=Math.atan2(b,a);0>
this.theta&&(this.theta+=2*Math.PI)},setp:function(a,b){this.theta=a;this.rho=b},clone:function(){return new t(this.theta,this.rho)},toComplex:function(a){var b=Math.cos(this.theta)*this.rho,c=Math.sin(this.theta)*this.rho;return a?{x:b,y:c}:new n(b,c)},add:function(a){return new t(this.theta+a.theta,this.rho+a.rho)},scale:function(a){return new t(this.theta,this.rho*a)},equals:function(a){return this.theta==a.theta&&this.rho==a.rho},$add:function(a){this.theta+=a.theta;this.rho+=a.rho;return this},
$madd:function(a){this.theta=(this.theta+a.theta)%(2*Math.PI);this.rho+=a.rho;return this},$scale:function(a){this.rho*=a;return this},isZero:function(){var a=Math.abs;return 1E-4>a(this.theta)&&1E-4>a(this.rho)},interpolate:function(a,b){var c=Math.PI,d=2*c,e=function(a){return 0>a?a%d+d:a%d},g=this.theta,h=a.theta,f=Math.abs(g-h);return{theta:f==c?g>h?e(h+(g-d-h)*b):e(h-d+(g-h)*b):f>=c?g>h?e(h+(g-d-h)*b):e(h-d+(g-(h-d))*b):e(h+(g-h)*b),rho:(this.rho-a.rho)*b+a.rho}}};t.KER=new t(0,0);var n=function(a,
b){this.x=a||0;this.y=b||0};$jit.Complex=n;n.prototype={getc:function(){return this},getp:function(a){return this.toPolar(a)},set:function(a){a=a.getc(!0);this.x=a.x;this.y=a.y},setc:function(a,b){this.x=a;this.y=b},setp:function(a,b){this.x=Math.cos(a)*b;this.y=Math.sin(a)*b},clone:function(){return new n(this.x,this.y)},toPolar:function(a){var b=this.norm(),c=Math.atan2(this.y,this.x);0>c&&(c+=2*Math.PI);return a?{theta:c,rho:b}:new t(c,b)},norm:function(){return Math.sqrt(this.squaredNorm())},
squaredNorm:function(){return this.x*this.x+this.y*this.y},add:function(a){return new n(this.x+a.x,this.y+a.y)},prod:function(a){return new n(this.x*a.x-this.y*a.y,this.y*a.x+this.x*a.y)},conjugate:function(){return new n(this.x,-this.y)},scale:function(a){return new n(this.x*a,this.y*a)},equals:function(a){return this.x==a.x&&this.y==a.y},$add:function(a){this.x+=a.x;this.y+=a.y;return this},$prod:function(a){var b=this.x,c=this.y;this.x=b*a.x-c*a.y;this.y=c*a.x+b*a.y;return this},$conjugate:function(){this.y=
-this.y;return this},$scale:function(a){this.x*=a;this.y*=a;return this},$div:function(a){var b=this.x,c=this.y,d=a.squaredNorm();this.x=b*a.x+c*a.y;this.y=c*a.x-b*a.y;return this.$scale(1/d)},isZero:function(){var a=Math.abs;return 1E-4>a(this.x)&&1E-4>a(this.y)}};n.KER=new n(0,0);$jit.Graph=new i({initialize:function(a,b,c,d){var e={klass:n,Node:{}};this.Node=b;this.Edge=c;this.Label=d;this.opt=f.merge(e,a||{});this.nodes={};this.edges={};var g=this;this.nodeList={};for(var h in A)g.nodeList[h]=
function(a){return function(){var b=Array.prototype.slice.call(arguments);g.eachNode(function(c){c[a].apply(c,b)})}}(h)},getNode:function(a){return this.hasNode(a)?this.nodes[a]:!1},get:function(a){return this.getNode(a)},getByName:function(a){for(var b in this.nodes){var c=this.nodes[b];if(c.name==a)return c}return!1},getAdjacence:function(a,b){return a in this.edges?this.edges[a][b]:!1},addNode:function(a){if(!this.nodes[a.id]){var b=this.edges[a.id]={};this.nodes[a.id]=new l.Node(f.extend({id:a.id,
name:a.name,data:f.merge(a.data||{},{}),adjacencies:b},this.opt.Node),this.opt.klass,this.Node,this.Edge,this.Label)}return this.nodes[a.id]},addAdjacence:function(a,b,c){this.hasNode(a.id)||this.addNode(a);this.hasNode(b.id)||this.addNode(b);a=this.nodes[a.id];b=this.nodes[b.id];if(!a.adjacentTo(b)){var d=this.edges[a.id]=this.edges[a.id]||{},e=this.edges[b.id]=this.edges[b.id]||{};d[b.id]=e[a.id]=new l.Adjacence(a,b,c,this.Edge,this.Label);return d[b.id]}return this.edges[a.id][b.id]},removeNode:function(a){if(this.hasNode(a)){delete this.nodes[a];
var b=this.edges[a],c;for(c in b)delete this.edges[c][a];delete this.edges[a]}},removeAdjacence:function(a,b){delete this.edges[a][b];delete this.edges[b][a]},hasNode:function(a){return a in this.nodes},empty:function(){this.nodes={};this.edges={}}});var l=$jit.Graph,A,H=function(a,b,c,d,e){var g,c=c||"current";"current"==c?g=this.data:"start"==c?g=this.startData:"end"==c&&(g=this.endData);a="$"+(a?a+"-":"")+b;return d?g[a]:!this.Config.overridable?e[b]||0:a in g?g[a]:a in this.data?this.data[a]:
e[b]||0},I=function(a,b,c,d){var d=d||"current",e;"current"==d?e=this.data:"start"==d?e=this.startData:"end"==d&&(e=this.endData);e["$"+(a?a+"-":"")+b]=c},J=function(a,b){var a="$"+(a?a+"-":""),c=this;f.each(b,function(b){b=a+b;delete c.data[b];delete c.endData[b];delete c.startData[b]})};A={getData:function(a,b,c){return H.call(this,"",a,b,c,this.Config)},setData:function(a,b,c){I.call(this,"",a,b,c)},setDataset:function(a,b){var a=f.splat(a),c;for(c in b)for(var d=0,e=f.splat(b[c]),g=a.length;d<
g;d++)this.setData(c,e[d],a[d])},removeData:function(){J.call(this,"",Array.prototype.slice.call(arguments))},getCanvasStyle:function(a,b,c){return H.call(this,"canvas",a,b,c,this.Config.CanvasStyles)},setCanvasStyle:function(a,b,c){I.call(this,"canvas",a,b,c)},setCanvasStyles:function(a,b){var a=f.splat(a),c;for(c in b)for(var d=0,e=f.splat(b[c]),g=a.length;d<g;d++)this.setCanvasStyle(c,e[d],a[d])},removeCanvasStyle:function(){J.call(this,"canvas",Array.prototype.slice.call(arguments))},getLabelData:function(a,
b,c){return H.call(this,"label",a,b,c,this.Label)},setLabelData:function(a,b,c){I.call(this,"label",a,b,c)},setLabelDataset:function(a,b){var a=f.splat(a),c;for(c in b)for(var d=0,e=f.splat(b[c]),g=a.length;d<g;d++)this.setLabelData(c,e[d],a[d])},removeLabelData:function(){J.call(this,"label",Array.prototype.slice.call(arguments))}};l.Node=new i({initialize:function(a,b,c,d,e){b={id:"",name:"",data:{},startData:{},endData:{},adjacencies:{},selected:!1,drawn:!1,exist:!1,angleSpan:{begin:0,end:0},pos:new b,
startPos:new b,endPos:new b};f.extend(this,f.extend(b,a));this.Config=this.Node=c;this.Edge=d;this.Label=e},adjacentTo:function(a){return a.id in this.adjacencies},getAdjacency:function(a){return this.adjacencies[a]},getPos:function(a){a=a||"current";if("current"==a)return this.pos;if("end"==a)return this.endPos;if("start"==a)return this.startPos},setPos:function(a,b){var b=b||"current",c;"current"==b?c=this.pos:"end"==b?c=this.endPos:"start"==b&&(c=this.startPos);c.set(a)}});l.Node.implement(A);
l.Adjacence=new i({initialize:function(a,b,c,d,e){this.nodeFrom=a;this.nodeTo=b;this.data=c||{};this.startData={};this.endData={};this.Config=this.Edge=d;this.Label=e}});l.Adjacence.implement(A);l.Util={filter:function(a){if(!a||"string"!=f.type(a))return function(){return!0};var b=a.split(" ");return function(a){for(var d=0;d<b.length;d++)if(a[b[d]])return!1;return!0}},getNode:function(a,b){return a.nodes[b]},eachNode:function(a,b,c){var c=this.filter(c),d;for(d in a.nodes)c(a.nodes[d])&&b(a.nodes[d])},
each:function(a,b,c){this.eachNode(a,b,c)},eachAdjacency:function(a,b,c){var d=a.adjacencies,c=this.filter(c),e;for(e in d){var g=d[e];if(c(g)){if(g.nodeFrom!=a){var h=g.nodeFrom;g.nodeFrom=g.nodeTo;g.nodeTo=h}b(g,e)}}},computeLevels:function(a,b,c,d){var c=c||0,e=this.filter(d);this.eachNode(a,function(a){a._flag=!1;a._depth=-1},d);a=a.getNode(b);a._depth=c;for(var g=[a];0!=g.length;){var h=g.pop();h._flag=!0;this.eachAdjacency(h,function(a){a=a.nodeTo;!1==a._flag&&e(a)&&(0>a._depth&&(a._depth=h._depth+
1+c),g.unshift(a))},d)}},eachBFS:function(a,b,c,d){var e=this.filter(d);this.clean(a);for(var g=[a.getNode(b)];0!=g.length;)a=g.pop(),a._flag=!0,c(a,a._depth),this.eachAdjacency(a,function(a){a=a.nodeTo;!1==a._flag&&e(a)&&(a._flag=!0,g.unshift(a))},d)},eachLevel:function(a,b,c,d,e){var g=a._depth,h=this.filter(e),f=this,c=!1===c?Number.MAX_VALUE-g:c;(function m(a,b,c){var e=a._depth;e>=b&&(e<=c&&h(a))&&d(a,e);e<c&&f.eachAdjacency(a,function(a){a=a.nodeTo;a._depth>e&&m(a,b,c)})})(a,b+g,c+g)},eachSubgraph:function(a,
b,c){this.eachLevel(a,0,!1,b,c)},eachSubnode:function(a,b,c){this.eachLevel(a,1,1,b,c)},anySubnode:function(a,b,c){var d=!1,b=b||f.lambda(!0),e="string"==f.type(b)?function(a){return a[b]}:b;this.eachSubnode(a,function(a){e(a)&&(d=!0)},c);return d},getSubnodes:function(a,b,c){var d=[],b=b||0,e;"array"==f.type(b)?(e=b[0],b=b[1]):(e=b,b=Number.MAX_VALUE-a._depth);this.eachLevel(a,e,b,function(a){d.push(a)},c);return d},getParents:function(a){var b=[];this.eachAdjacency(a,function(c){c=c.nodeTo;c._depth<
a._depth&&b.push(c)});return b},isDescendantOf:function(a,b){if(a.id==b)return!0;for(var c=this.getParents(a),d=!1,e=0;!d&&e<c.length;e++)d=d||this.isDescendantOf(c[e],b);return d},clean:function(a){this.eachNode(a,function(a){a._flag=!1})},getClosestNodeToOrigin:function(a,b,c){return this.getClosestNodeToPos(a,t.KER,b,c)},getClosestNodeToPos:function(a,b,c,d){var e=null,c=c||"current",b=b&&b.getc(!0)||n.KER,g=function(a,b){var c=a.x-b.x,d=a.y-b.y;return c*c+d*d};this.eachNode(a,function(a){e=null==
e||g(a.getPos(c).getc(!0),b)<g(e.getPos(c).getc(!0),b)?a:e},d);return e}};f.each("get getNode each eachNode computeLevels eachBFS clean getClosestNodeToPos getClosestNodeToOrigin".split(" "),function(a){l.prototype[a]=function(){return l.Util[a].apply(l.Util,[this].concat(Array.prototype.slice.call(arguments)))}});f.each("eachAdjacency eachLevel eachSubgraph eachSubnode anySubnode getSubnodes getParents isDescendantOf".split(" "),function(a){l.Node.prototype[a]=function(){return l.Util[a].apply(l.Util,
[this].concat(Array.prototype.slice.call(arguments)))}});l.Op={options:{type:"nothing",duration:2E3,hideLabels:!0,fps:30},initialize:function(a){this.viz=a},removeNode:function(a,b){var c=this.viz,d=f.merge(this.options,c.controller,b),e=f.splat(a),g,h,j;switch(d.type){case "nothing":for(g=0;g<e.length;g++)c.graph.removeNode(e[g]);break;case "replot":this.removeNode(e,{type:"nothing"});c.labels.clearLabels();c.refresh(!0);break;case "fade:seq":case "fade":h=this;for(g=0;g<e.length;g++)j=c.graph.getNode(e[g]),
j.setData("alpha",0,"end");c.fx.animate(f.merge(d,{modes:["node-property:alpha"],onComplete:function(){h.removeNode(e,{type:"nothing"});c.labels.clearLabels();c.reposition();c.fx.animate(f.merge(d,{modes:["linear"]}))}}));break;case "fade:con":h=this;for(g=0;g<e.length;g++)j=c.graph.getNode(e[g]),j.setData("alpha",0,"end"),j.ignore=!0;c.reposition();c.fx.animate(f.merge(d,{modes:["node-property:alpha","linear"],onComplete:function(){h.removeNode(e,{type:"nothing"});d.onComplete&&d.onComplete()}}));
break;case "iter":h=this;c.fx.sequence({condition:function(){return 0!=e.length},step:function(){h.removeNode(e.shift(),{type:"nothing"});c.labels.clearLabels()},onComplete:function(){d.onComplete&&d.onComplete()},duration:Math.ceil(d.duration/e.length)});break;default:this.doError()}},removeEdge:function(a,b){var c=this.viz,d=f.merge(this.options,c.controller,b),e="string"==f.type(a[0])?[a]:a,g,h,j;switch(d.type){case "nothing":for(g=0;g<e.length;g++)c.graph.removeAdjacence(e[g][0],e[g][1]);break;
case "replot":this.removeEdge(e,{type:"nothing"});c.refresh(!0);break;case "fade:seq":case "fade":h=this;for(g=0;g<e.length;g++)(j=c.graph.getAdjacence(e[g][0],e[g][1]))&&j.setData("alpha",0,"end");c.fx.animate(f.merge(d,{modes:["edge-property:alpha"],onComplete:function(){h.removeEdge(e,{type:"nothing"});c.reposition();c.fx.animate(f.merge(d,{modes:["linear"]}))}}));break;case "fade:con":h=this;for(g=0;g<e.length;g++)if(j=c.graph.getAdjacence(e[g][0],e[g][1]))j.setData("alpha",0,"end"),j.ignore=
!0;c.reposition();c.fx.animate(f.merge(d,{modes:["edge-property:alpha","linear"],onComplete:function(){h.removeEdge(e,{type:"nothing"});d.onComplete&&d.onComplete()}}));break;case "iter":h=this;c.fx.sequence({condition:function(){return 0!=e.length},step:function(){h.removeEdge(e.shift(),{type:"nothing"});c.labels.clearLabels()},onComplete:function(){d.onComplete()},duration:Math.ceil(d.duration/e.length)});break;default:this.doError()}},sum:function(a,b){var c=this.viz,d=f.merge(this.options,c.controller,
b),e=c.root,g;c.root=b.id||c.root;switch(d.type){case "nothing":g=c.construct(a);g.eachNode(function(a){a.eachAdjacency(function(a){c.graph.addAdjacence(a.nodeFrom,a.nodeTo,a.data)})});break;case "replot":c.refresh(!0);this.sum(a,{type:"nothing"});c.refresh(!0);break;case "fade:seq":case "fade":case "fade:con":that=this;g=c.construct(a);var h=!this.preprocessSum(g)?["node-property:alpha"]:["node-property:alpha","edge-property:alpha"];c.reposition();"fade:con"!=d.type?c.fx.animate(f.merge(d,{modes:["linear"],
onComplete:function(){c.fx.animate(f.merge(d,{modes:h,onComplete:function(){d.onComplete()}}))}})):(c.graph.eachNode(function(a){a.id!=e&&a.pos.isZero()&&(a.pos.set(a.endPos),a.startPos.set(a.endPos))}),c.fx.animate(f.merge(d,{modes:["linear"].concat(h)})));break;default:this.doError()}},morph:function(a,b,c){var c=c||{},d=this.viz,e=f.merge(this.options,d.controller,b),g=d.root,h;d.root=b.id||d.root;switch(e.type){case "nothing":h=d.construct(a);h.eachNode(function(a){var b=d.graph.hasNode(a.id);
a.eachAdjacency(function(a){var b=!!d.graph.getAdjacence(a.nodeFrom.id,a.nodeTo.id);d.graph.addAdjacence(a.nodeFrom,a.nodeTo,a.data);if(b){var b=d.graph.getAdjacence(a.nodeFrom.id,a.nodeTo.id),c;for(c in a.data||{})b.data[c]=a.data[c]}});if(b){var b=d.graph.getNode(a.id),c;for(c in a.data||{})b.data[c]=a.data[c]}});d.graph.eachNode(function(a){a.eachAdjacency(function(a){h.getAdjacence(a.nodeFrom.id,a.nodeTo.id)||d.graph.removeAdjacence(a.nodeFrom.id,a.nodeTo.id)});h.hasNode(a.id)||d.graph.removeNode(a.id)});
break;case "replot":d.labels.clearLabels(!0);this.morph(a,{type:"nothing"});d.refresh(!0);d.refresh(!0);break;case "fade:seq":case "fade":case "fade:con":that=this;h=d.construct(a);var j="node-property"in c&&f.map(f.splat(c["node-property"]),function(a){return"$"+a});d.graph.eachNode(function(a){var b=h.getNode(a.id);if(b){var b=b.data,c;for(c in b)j&&-1<f.indexOf(j,c)?a.endData[c]=b[c]:a.data[c]=b[c]}else a.setData("alpha",1),a.setData("alpha",1,"start"),a.setData("alpha",0,"end"),a.ignore=!0});
d.graph.eachNode(function(a){a.ignore||a.eachAdjacency(function(a){if(!a.nodeFrom.ignore&&!a.nodeTo.ignore){var b=h.getNode(a.nodeFrom.id),a=h.getNode(a.nodeTo.id);b.adjacentTo(a)||(a=d.graph.getAdjacence(b.id,a.id),k=!0,a.setData("alpha",1),a.setData("alpha",1,"start"),a.setData("alpha",0,"end"))}})});var k=this.preprocessSum(h),a=!k?["node-property:alpha"]:["node-property:alpha","edge-property:alpha"];a[0]+="node-property"in c?":"+f.splat(c["node-property"]).join(":"):"";a[1]=(a[1]||"edge-property:alpha")+
("edge-property"in c?":"+f.splat(c["edge-property"]).join(":"):"");"label-property"in c&&a.push("label-property:"+f.splat(c["label-property"]).join(":"));d.reposition?d.reposition():d.compute("end");d.graph.eachNode(function(a){a.id!=g&&a.pos.getp().equals(t.KER)&&(a.pos.set(a.endPos),a.startPos.set(a.endPos))});d.fx.animate(f.merge(e,{modes:[c.position||"polar"].concat(a),onComplete:function(){d.graph.eachNode(function(a){a.ignore&&d.graph.removeNode(a.id)});d.graph.eachNode(function(a){a.eachAdjacency(function(a){a.ignore&&
d.graph.removeAdjacence(a.nodeFrom.id,a.nodeTo.id)})});e.onComplete()}}))}},contract:function(a,b){var c=this.viz;!a.collapsed&&a.anySubnode(f.lambda(!0))&&(b=f.merge(this.options,c.config,b||{},{modes:["node-property:alpha:span","linear"]}),a.collapsed=!0,function e(a){a.eachSubnode(function(a){a.ignore=!0;a.setData("alpha",0,"animate"==b.type?"end":"current");e(a)})}(a),"animate"==b.type?(c.compute("end"),c.rotated&&c.rotate(c.rotated,"none",{property:"end"}),function g(b){b.eachSubnode(function(b){b.setPos(a.getPos("end"),
"end");g(b)})}(a),c.fx.animate(b)):"replot"==b.type&&c.refresh())},expand:function(a,b){if("collapsed"in a){var c=this.viz,b=f.merge(this.options,c.config,b||{},{modes:["node-property:alpha:span","linear"]});delete a.collapsed;(function e(a){a.eachSubnode(function(a){delete a.ignore;a.setData("alpha",1,"animate"==b.type?"end":"current");e(a)})})(a);"animate"==b.type?(c.compute("end"),c.rotated&&c.rotate(c.rotated,"none",{property:"end"}),c.fx.animate(b)):"replot"==b.type&&c.refresh()}},preprocessSum:function(a){var b=
this.viz;a.eachNode(function(a){b.graph.hasNode(a.id)||(b.graph.addNode(a),a=b.graph.getNode(a.id),a.setData("alpha",0),a.setData("alpha",0,"start"),a.setData("alpha",1,"end"))});var c=!1;a.eachNode(function(a){a.eachAdjacency(function(a){var d=b.graph.getNode(a.nodeFrom.id),h=b.graph.getNode(a.nodeTo.id);d.adjacentTo(h)||(a=b.graph.addAdjacence(d,h,a.data),d.startAlpha==d.endAlpha&&h.startAlpha==h.endAlpha&&(c=!0,a.setData("alpha",0),a.setData("alpha",0,"start"),a.setData("alpha",1,"end")))})});
return c}};var K={none:{render:f.empty,contains:f.lambda(!1)},circle:{render:function(a,b,c,d){d=d.getCtx();d.beginPath();d.arc(b.x,b.y,c,0,2*Math.PI,!0);d.closePath();d[a]()},contains:function(a,b,c){var d=a.x-b.x,a=a.y-b.y;return d*d+a*a<=c*c}},ellipse:{render:function(a,b,c,d,e){var e=e.getCtx(),g=1,h=1,f=1,k=1,m=0;c>d?(m=c/2,h=d/c,k=c/d):(m=d/2,g=c/d,f=d/c);e.save();e.scale(g,h);e.beginPath();e.arc(b.x*f,b.y*k,m,0,2*Math.PI,!0);e.closePath();e[a]();e.restore()},contains:function(a,b,c,d){var e=
0,g=1,h=1,f=0,k=0;c>d?(e=c/2,h=d/c):(e=d/2,g=c/d);f=(a.x-b.x)*(1/g);k=(a.y-b.y)*(1/h);return f*f+k*k<=e*e}},square:{render:function(a,b,c,d){d.getCtx()[a+"Rect"](b.x-c,b.y-c,2*c,2*c)},contains:function(a,b,c){return Math.abs(b.x-a.x)<=c&&Math.abs(b.y-a.y)<=c}},rectangle:{render:function(a,b,c,d,e){e.getCtx()[a+"Rect"](b.x-c/2,b.y-d/2,c,d)},contains:function(a,b,c,d){return Math.abs(b.x-a.x)<=c/2&&Math.abs(b.y-a.y)<=d/2}},triangle:{render:function(a,b,c,d){var d=d.getCtx(),e=b.x,g=b.y-c,h=e-c,b=b.y+
c,c=e+c;d.beginPath();d.moveTo(e,g);d.lineTo(h,b);d.lineTo(c,b);d.closePath();d[a]()},contains:function(a,b,c){return K.circle.contains(a,b,c)}},star:{render:function(a,b,c,d){var d=d.getCtx(),e=Math.PI/5;d.save();d.translate(b.x,b.y);d.beginPath();d.moveTo(c,0);for(b=0;9>b;b++)d.rotate(e),0==b%2?d.lineTo(0.200811*(c/0.525731),0):d.lineTo(c,0);d.closePath();d[a]();d.restore()},contains:function(a,b,c){return K.circle.contains(a,b,c)}}},Q={line:{render:function(a,b,c){c=c.getCtx();c.beginPath();c.moveTo(a.x,
a.y);c.lineTo(b.x,b.y);c.stroke()},contains:function(a,b,c,d){var e=Math.min,g=Math.max,h=e(a.x,b.x),f=g(a.x,b.x),e=e(a.y,b.y),g=g(a.y,b.y);return c.x>=h&&c.x<=f&&c.y>=e&&c.y<=g?Math.abs(b.x-a.x)<=d?!0:Math.abs((b.y-a.y)/(b.x-a.x)*(c.x-a.x)+a.y-c.y)<=d:!1}},arrow:{render:function(a,b,c,d,e){e=e.getCtx();d&&(d=a,a=b,b=d);d=new n(b.x-a.x,b.y-a.y);d.$scale(c/d.norm());var c=new n(b.x-d.x,b.y-d.y),g=new n(-d.y/2,d.x/2),d=c.add(g),c=c.$add(g.$scale(-1));e.beginPath();e.moveTo(a.x,a.y);e.lineTo(b.x,b.y);
e.stroke();e.beginPath();e.moveTo(d.x,d.y);e.lineTo(c.x,c.y);e.lineTo(b.x,b.y);e.closePath();e.fill()},contains:function(a,b,c,d){return Q.line.contains(a,b,c,d)}},hyperline:{render:function(a,b,c,d){var e,g,h,f,k;function m(a,b){return a<b?a+Math.PI>b?!1:!0:b+Math.PI>a?!0:!1}d=d.getCtx();e=a.x*b.y-a.y*b.x;g=a.squaredNorm();k=b.squaredNorm();0==e?(g=e=0,h=-1,k=f=void 0):(f=(a.y*k-b.y*g+a.y-b.y)/e,k=(b.x*g-a.x*k+b.x-a.x)/e,e=-f/2,g=-k/2,h=(f*f+k*k)/4-1,0>h?(g=e=0,h=-1,k=f=void 0):(h=Math.sqrt(h),h=
1E3<h?-1:h));1E3<f||1E3<k||0>h?(d.beginPath(),d.moveTo(a.x*c,a.y*c),d.lineTo(b.x*c,b.y*c)):(b=Math.atan2(b.y-g,b.x-e),a=Math.atan2(a.y-g,a.x-e),m=m(b,a),d.beginPath(),d.arc(e*c,g*c,h*c,b,a,m));d.stroke()},contains:f.lambda(!1)}};l.Plot={initialize:function(a,b){this.viz=a;this.config=a.config;this.node=a.config.Node;this.edge=a.config.Edge;this.animation=new C;this.nodeTypes=new b.Plot.NodeTypes;this.edgeTypes=new b.Plot.EdgeTypes;this.labels=a.labels},nodeHelper:K,edgeHelper:Q,Interpolator:{map:{border:"color",
color:"color",width:"number",height:"number",dim:"number",alpha:"number",lineWidth:"number",angularWidth:"number",span:"number",valueArray:"array-number",dimArray:"array-number"},canvas:{globalAlpha:"number",fillStyle:"color",strokeStyle:"color",lineWidth:"number",shadowBlur:"number",shadowColor:"color",shadowOffsetX:"number",shadowOffsetY:"number",miterLimit:"number"},label:{size:"number",color:"color"},compute:function(a,b,c){return a+(b-a)*c},moebius:function(a,b,c,d){b=d.scale(-c);if(1>b.norm()){var c=
b.x,d=b.y,e=a.startPos.getc().moebiusTransformation(b);a.pos.setc(e.x,e.y);b.x=c;b.y=d}},linear:function(a,b,c){var b=a.startPos.getc(!0),d=a.endPos.getc(!0);a.pos.setc(this.compute(b.x,d.x,c),this.compute(b.y,d.y,c))},polar:function(a,b,c){b=a.startPos.getp(!0);c=a.endPos.getp().interpolate(b,c);a.pos.setp(c.theta,c.rho)},number:function(a,b,c,d,e){var g=a[d](b,"start"),d=a[d](b,"end");a[e](b,this.compute(g,d,c))},color:function(a,b,c,d,e){var g=f.hexToRgb(a[d](b,"start")),d=f.hexToRgb(a[d](b,"end")),
h=this.compute,c=f.rgbToHex([parseInt(h(g[0],d[0],c)),parseInt(h(g[1],d[1],c)),parseInt(h(g[2],d[2],c))]);a[e](b,c)},"array-number":function(a,b,c,d,e){for(var g=a[d](b,"start"),d=a[d](b,"end"),h=[],f=0,k=g.length;f<k;f++){var m=g[f],D=d[f];if(m.length){for(var i=0,s=m.length,l=[];i<s;i++)l.push(this.compute(m[i],D[i],c));h.push(l)}else h.push(this.compute(m,D,c))}a[e](b,h)},node:function(a,b,c,d,e,g){d=this[d];if(b)for(var h=b.length,f=0;f<h;f++){var k=b[f];this[d[k]](a,k,c,e,g)}else for(k in d)this[d[k]](a,
k,c,e,g)},edge:function(a,b,c,d,e,g){var a=a.adjacencies,h;for(h in a)this.node(a[h],b,c,d,e,g)},"node-property":function(a,b,c){this.node(a,b,c,"map","getData","setData")},"edge-property":function(a,b,c){this.edge(a,b,c,"map","getData","setData")},"label-property":function(a,b,c){this.node(a,b,c,"label","getLabelData","setLabelData")},"node-style":function(a,b,c){this.node(a,b,c,"canvas","getCanvasStyle","setCanvasStyle")},"edge-style":function(a,b,c){this.edge(a,b,c,"canvas","getCanvasStyle","setCanvasStyle")}},
sequence:function(a){var b=this,a=f.merge({condition:f.lambda(!1),step:f.empty,onComplete:f.empty,duration:200},a||{}),c=setInterval(function(){a.condition()?a.step():(clearInterval(c),a.onComplete());b.viz.refresh(!0)},a.duration)},prepare:function(a){var b=this.viz.graph,c={"node-property":{getter:"getData",setter:"setData"},"edge-property":{getter:"getData",setter:"setData"},"node-style":{getter:"getCanvasStyle",setter:"setCanvasStyle"},"edge-style":{getter:"getCanvasStyle",setter:"setCanvasStyle"}},
d={};if("array"==f.type(a))for(var e=0,g=a.length;e<g;e++){var h=a[e].split(":");d[h.shift()]=h}else for(e in a)"position"==e?d[a.position]=[]:d[e]=f.splat(a[e]);b.eachNode(function(a){a.startPos.set(a.pos);f.each(["node-property","node-style"],function(b){if(b in d)for(var e=d[b],g=0,h=e.length;g<h;g++)a[c[b].setter](e[g],a[c[b].getter](e[g]),"start")});f.each(["edge-property","edge-style"],function(b){if(b in d){var e=d[b];a.eachAdjacency(function(a){for(var d=0,g=e.length;d<g;d++)a[c[b].setter](e[d],
a[c[b].getter](e[d]),"start")})}})});return d},animate:function(a,b){var a=f.merge(this.viz.config,a||{}),c=this,d=this.viz.graph,e=this.Interpolator,g="nodefx"===a.type?this.nodeFxAnimation:this.animation,h=this.prepare(a.modes);a.hideLabels&&this.labels.hideLabels(!0);g.setOptions(f.extend(a,{$animating:!1,compute:function(g){d.eachNode(function(a){for(var c in h)e[c](a,h[c],g,b)});c.plot(a,this.$animating,g);this.$animating=!0},complete:function(){a.hideLabels&&c.labels.hideLabels(!1);c.plot(a);
a.onComplete()}})).start()},nodeFx:function(a){var b=this.viz,c=b.graph,d=this.nodeFxAnimation,e=f.merge(this.viz.config,{elements:{id:!1,properties:{}},reposition:!1}),a=f.merge(e,a||{},{onBeforeCompute:f.empty,onAfterCompute:f.empty});d.stopTimer();var g=a.elements.properties;a.elements.id?(d=f.splat(a.elements.id),f.each(d,function(a){if(a=c.getNode(a))for(var b in g)a.setData(b,g[b],"end")})):c.eachNode(function(a){for(var b in g)a.setData(b,g[b],"end")});var d=[],h;for(h in g)d.push(h);h=["node-property:"+
d.join(":")];a.reposition&&(h.push("linear"),b.compute("end"));this.animate(f.merge(a,{modes:h,type:"nodefx"}))},plot:function(a,b){var c=this.viz,d=c.graph,e=c.canvas,c=c.root,g=this;e.getCtx();a=a||this.viz.controller;a.clearCanvas&&e.clear();if(c=d.getNode(c)){var h=!!c.visited;d.eachNode(function(c){var d=c.getData("alpha");c.eachAdjacency(function(d){var f=d.nodeTo;!!f.visited===h&&(c.drawn&&f.drawn)&&(!b&&a.onBeforePlotLine(d),g.plotLine(d,e,b),!b&&a.onAfterPlotLine(d))});c.drawn&&(!b&&a.onBeforePlotNode(c),
g.plotNode(c,e,b),!b&&a.onAfterPlotNode(c));!g.labelsHidden&&a.withLabels&&(c.drawn&&0.95<=d?g.labels.plotLabel(e,c,a):g.labels.hideLabel(c,!1));c.visited=!h})}},plotTree:function(a,b,c){var d=this,e=this.viz.canvas;e.getCtx();var g=a.getData("alpha");a.eachSubnode(function(g){if(b.plotSubtree(a,g)&&g.exist&&g.drawn){var f=a.getAdjacency(g.id);!c&&b.onBeforePlotLine(f);d.plotLine(f,e,c);!c&&b.onAfterPlotLine(f);d.plotTree(g,b,c)}});a.drawn?(!c&&b.onBeforePlotNode(a),this.plotNode(a,e,c),!c&&b.onAfterPlotNode(a),
!b.hideLabels&&b.withLabels&&0.95<=g?this.labels.plotLabel(e,a,b):this.labels.hideLabel(a,!1)):this.labels.hideLabel(a,!0)},plotNode:function(a,b,c){var d=a.getData("type"),e=this.node.CanvasStyles;if("none"!=d){var g=a.getData("lineWidth"),f=a.getData("color"),j=a.getData("alpha"),k=b.getCtx();k.save();k.lineWidth=g;k.fillStyle=k.strokeStyle=f;k.globalAlpha=j;for(var m in e)k[m]=a.getCanvasStyle(m);this.nodeTypes[d].render.call(this,a,b,c);k.restore()}},plotLine:function(a,b,c){var d=a.getData("type"),
e=this.edge.CanvasStyles;if("none"!=d){var g=a.getData("lineWidth"),f=a.getData("color"),j=b.getCtx(),k=a.nodeFrom,m=a.nodeTo;j.save();j.lineWidth=g;j.fillStyle=j.strokeStyle=f;j.globalAlpha=Math.min(k.getData("alpha"),m.getData("alpha"),a.getData("alpha"));for(var i in e)j[i]=a.getCanvasStyle(i);this.edgeTypes[d].render.call(this,a,b,c);j.restore()}}};l.Plot3D=f.merge(l.Plot,{Interpolator:{linear:function(a,b,c){var b=a.startPos.getc(!0),d=a.endPos.getc(!0);a.pos.setc(this.compute(b.x,d.x,c),this.compute(b.y,
d.y,c),this.compute(b.z,d.z,c))}},plotNode:function(a,b){"none"!=a.getData("type")&&this.plotElement(a,b,{getAlpha:function(){return a.getData("alpha")}})},plotLine:function(a,b){"none"!=a.getData("type")&&this.plotElement(a,b,{getAlpha:function(){return Math.min(a.nodeFrom.getData("alpha"),a.nodeTo.getData("alpha"),a.getData("alpha"))}})},plotElement:function(a,b,c){var d=b.getCtx(),e=new Matrix4,g=b.config.Scene.Lighting,h=b.canvases[0],b=h.program,h=h.camera;a.geometry||(a.geometry=new (O3D[a.getData("type")]));
a.geometry.update(a);if(!a.webGLVertexBuffer){for(var j=[],k=[],m=[],i=0,l=a.geometry,s=0,n=l.vertices,l=l.faces,o=l.length;s<o;s++){var r=l[s],p=n[r.a],t=n[r.b],u=n[r.c],q=r.d?n[r.d]:!1,r=r.normal;j.push(p.x,p.y,p.z);j.push(t.x,t.y,t.z);j.push(u.x,u.y,u.z);q&&j.push(q.x,q.y,q.z);m.push(r.x,r.y,r.z);m.push(r.x,r.y,r.z);m.push(r.x,r.y,r.z);q&&m.push(r.x,r.y,r.z);k.push(i,i+1,i+2);q?(k.push(i,i+2,i+3),i+=4):i+=3}a.webGLVertexBuffer=d.createBuffer();d.bindBuffer(d.ARRAY_BUFFER,a.webGLVertexBuffer);d.bufferData(d.ARRAY_BUFFER,
new Float32Array(j),d.STATIC_DRAW);a.webGLFaceBuffer=d.createBuffer();d.bindBuffer(d.ELEMENT_ARRAY_BUFFER,a.webGLFaceBuffer);d.bufferData(d.ELEMENT_ARRAY_BUFFER,new Uint16Array(k),d.STATIC_DRAW);a.webGLFaceCount=k.length;a.webGLNormalBuffer=d.createBuffer();d.bindBuffer(d.ARRAY_BUFFER,a.webGLNormalBuffer);d.bufferData(d.ARRAY_BUFFER,new Float32Array(m),d.STATIC_DRAW)}e.multiply(h.matrix,a.geometry.matrix);d.uniformMatrix4fv(b.viewMatrix,!1,e.flatten());d.uniformMatrix4fv(b.projectionMatrix,!1,h.projectionMatrix.flatten());
e=Matrix4.makeInvert(e);e.$transpose();d.uniformMatrix4fv(b.normalMatrix,!1,e.flatten());e=f.hexToRgb(a.getData("color"));e.push(c.getAlpha());d.uniform4f(b.color,e[0]/255,e[1]/255,e[2]/255,e[3]);d.uniform1i(b.enableLighting,g.enable);if(g.enable&&(g.ambient&&(c=g.ambient,d.uniform3f(b.ambientColor,c[0],c[1],c[2])),g.directional))g=g.directional,e=g.color,g=g.direction,g=(new Vector3(g.x,g.y,g.z)).normalize().$scale(-1),d.uniform3f(b.lightingDirection,g.x,g.y,g.z),d.uniform3f(b.directionalColor,e[0],
e[1],e[2]);d.bindBuffer(d.ARRAY_BUFFER,a.webGLVertexBuffer);d.vertexAttribPointer(b.position,3,d.FLOAT,!1,0,0);d.bindBuffer(d.ARRAY_BUFFER,a.webGLNormalBuffer);d.vertexAttribPointer(b.normal,3,d.FLOAT,!1,0,0);d.bindBuffer(d.ELEMENT_ARRAY_BUFFER,a.webGLFaceBuffer);d.drawElements(d.TRIANGLES,a.webGLFaceCount,d.UNSIGNED_SHORT,0)}});l.Label={};l.Label.Native=new i({initialize:function(a){this.viz=a},plotLabel:function(a,b,c){var d=a.getCtx();b.pos.getc(!0);d.font=b.getLabelData("style")+" "+b.getLabelData("size")+
"px "+b.getLabelData("family");d.textAlign=b.getLabelData("textAlign");d.fillStyle=d.strokeStyle=b.getLabelData("color");d.textBaseline=b.getLabelData("textBaseline");this.renderLabel(a,b,c)},renderLabel:function(a,b){var c=a.getCtx(),d=b.pos.getc(!0);c.fillText(b.name,d.x,d.y+b.getData("height")/2)},hideLabel:f.empty,hideLabels:f.empty});l.Label.DOM=new i({labelsHidden:!1,labelContainer:!1,labels:{},getLabelContainer:function(){return this.labelContainer?this.labelContainer:this.labelContainer=document.getElementById(this.viz.config.labelContainer)},
getLabel:function(a){return a in this.labels&&null!=this.labels[a]?this.labels[a]:this.labels[a]=document.getElementById(a)},hideLabels:function(a){this.getLabelContainer().style.display=a?"none":"";this.labelsHidden=a},clearLabels:function(a){for(var b in this.labels)if(a||!this.viz.graph.hasNode(b))this.disposeLabel(b),delete this.labels[b]},disposeLabel:function(a){(a=this.getLabel(a))&&a.parentNode&&a.parentNode.removeChild(a)},hideLabel:function(a,b){var a=f.splat(a),c=b?"":"none",d=this;f.each(a,
function(a){if(a=d.getLabel(a.id))a.style.display=c})},fitsInCanvas:function(a,b){var c=b.getSize();return a.x>=c.width||0>a.x||a.y>=c.height||0>a.y?!1:!0}});l.Label.HTML=new i({Implements:l.Label.DOM,plotLabel:function(a,b,c){var a=b.id,d=this.getLabel(a);if(!d&&!(d=document.getElementById(a))){var d=document.createElement("div"),e=this.getLabelContainer();d.id=a;d.className="node";d.style.position="absolute";c.onCreateLabel(d,b);e.appendChild(d);this.labels[b.id]=d}this.placeLabel(d,b,c)}});l.Label.SVG=
new i({Implements:l.Label.DOM,plotLabel:function(a,b,c){var a=b.id,d=this.getLabel(a);if(!d&&!(d=document.getElementById(a))){var d=document.createElementNS("http://www.w3.org/2000/svg","svg:text"),e=document.createElementNS("http://www.w3.org/2000/svg","svg:tspan");d.appendChild(e);e=this.getLabelContainer();d.setAttribute("id",a);d.setAttribute("class","node");e.appendChild(d);c.onCreateLabel(d,b);this.labels[b.id]=d}this.placeLabel(d,b,c)}});l.Geom=new i({initialize:function(a){this.viz=a;this.config=
a.config;this.node=a.config.Node;this.edge=a.config.Edge},translate:function(a,b){b=f.splat(b);this.viz.graph.eachNode(function(c){f.each(b,function(b){c.getPos(b).$add(a)})})},setRightLevelToShow:function(a,b,c){var d=this.getRightLevelToShow(a,b),e=this.viz.labels,g=f.merge({execShow:!0,execHide:!0,onHide:f.empty,onShow:f.empty},c||{});a.eachLevel(0,this.config.levelsToShow,function(b){b._depth-a._depth>d?(g.onHide(b),g.execHide&&(b.drawn=!1,b.exist=!1,e.hideLabel(b,!1))):(g.onShow(b),g.execShow&&
(b.exist=!0))});a.drawn=!0},getRightLevelToShow:function(a,b){var c=this.config,d=c.levelsToShow;if(!c.constrained)return d;for(;!this.treeFitsInCanvas(a,b,d)&&1<d;)d--;return d}});var p=$jit.Layouts={},W={label:null,compute:function(a,b,c){this.initializeLabel(c);var d=this.label,e=d.style;a.eachNode(function(a){var b=a.getData("autoWidth"),c=a.getData("autoHeight");if(b||c){delete a.data.$width;delete a.data.$height;delete a.data.$dim;var k=a.getData("width"),m=a.getData("height");e.width=b?"auto":
k+"px";e.height=c?"auto":m+"px";d.innerHTML=a.name;b=d.offsetWidth;c=d.offsetHeight;k=a.getData("type");-1===f.indexOf(["circle","square","triangle","star"],k)?(a.setData("width",b),a.setData("height",c)):(b=b>c?b:c,a.setData("width",b),a.setData("height",b),a.setData("dim",b))}})},initializeLabel:function(a){this.label||(this.label=document.createElement("div"),document.body.appendChild(this.label));this.setLabelStyles(a)},setLabelStyles:function(){f.extend(this.label.style,{visibility:"hidden",
position:"absolute",width:"auto",height:"auto"});this.label.className="jit-autoadjust-label"}},L=function(a,b){var c=[];f.each(a,function(a){a=R.call(a);a[0]+=b;a[1]+=b;c.push(a)});return c},G=function(a,b){if(0==a.length)return b;if(0==b.length)return a;var c=a.shift(),d=b.shift();return[[c[0],d[1]]].concat(G(a,b))},S=function(a,b){b=b||[];if(0==a.length)return b;var c=a.pop();return S(a,G(c,b))},M=function(a,b,c,d,e){if(a.length<=e||b.length<=e)return 0;var g=a[e][1],f=b[e][0];return Math.max(M(a,
b,c,d,++e)+c,g-f+d)},R=Array.prototype.slice,q=new i({compute:function(a,b){var c=a||"start",d=this.graph.getNode(this.root);f.extend(d,{drawn:!0,exist:!0,selected:!0});W.compute(this.graph,c,this.config);(b||!("_depth"in d))&&this.graph.computeLevels(this.root,0,"ignore");this.computePositions(d,c)},computePositions:function(a,b){var c=this.config,d=c.multitree,e=c.align,g="center"!==e&&c.indent,c=c.orientation,h=this;f.each(d?["top","right","bottom","left"]:[c],function(c){var f=h.graph,m=h.config,
i=function(a,d,e){var g=a.getData(q,b),h=[],s=[],n=!1,p=(d||a.getData(t,b))+m.levelDistance;a.eachSubnode(function(a){if(a.exist&&(!l||"$orn"in a.data&&a.data.$orn==c)){if(!n){var d=a._depth,g=m.Node,r=m.multitree;if(g.overridable){var o=-1,q=-1;f.eachNode(function(a){if(a._depth==d&&(!r||"$orn"in a.data&&a.data.$orn==c)){var e=a.getData("width",b),a=a.getData("height",b);o=o<e?e:o;q=q<a?a:q}});n={width:0>o?g.width:o,height:0>q?g.height:q}}else n=g}a=i(a,n[t],e+p);h.push(a.tree);s.push(a.extent)}});
var w=y,A=u,d=z,v,C=function(a,b,c){if(b.length<=c)return[];var d=b[c],e=M(a,d,w,A,0);return[e].concat(C(G(a,L(d,e)),b,++c))};v=C([],s,0);var x,O=function(a,b,c){if(b.length<=c)return[];var d=b[c],e=-M(d,a,w,A,0);return[e].concat(O(G(L(d,e),a),b,++c))};x=R.call(s);x=O([],x.reverse(),0).reverse();"left"==d?x=v:"right"==d&&(v=x);for(var B=0,d=[];B<v.length;B++)d[B]=(v[B]+x[B])/2;v=0;for(x=[];v<h.length;v++){var B=d[v],F="left"==c||"right"==c?"y":"x";h[v].getPos(b)[F]+=B;x.push(L(s[v],d[v]))}g=[[-g/
2,g/2]].concat(S(x));a.getPos(b)[r]=0;"top"==c||"left"==c?a.getPos(b)[o]=e:a.getPos(b)[o]=-e;return{tree:a,extent:g}},l=m.multitree,s=["x","y"],n=["width","height"],p=+("left"==c||"right"==c),r=s[p],o=s[1-p],q=n[p],t=n[1-p],u=m.siblingOffset,y=m.subtreeOffset,z=m.align;i(a,!1,0);var w=["x","y"][+("left"==c||"right"==c)];(function X(a){a.eachSubnode(function(f){if(f.exist&&(!d||"$orn"in f.data&&f.data.$orn==c))f.getPos(b)[w]+=a.getPos(b)[w],g&&(f.getPos(b)[w]+="left"==e?g:-g),X(f)})})(a)})}});p.Tree=
q;var q=$jit,T=function(a){a=a||this.clickedNode;if(!this.config.constrained)return[];var b=this.geom,c=this.canvas,d=a._depth,e=[];this.graph.eachNode(function(b){b.exist&&!b.selected&&(b.isDescendantOf(a.id)?b._depth<=d&&e.push(b):e.push(b))});b=b.getRightLevelToShow(a,c);a.eachLevel(b,b,function(a){a.exist&&!a.selected&&e.push(a)});for(b=0;b<w.length;b++)c=this.graph.getNode(w[b]),c.isDescendantOf(a.id)||e.push(c);return e},U=function(){var a=[],b=this.config;this.clickedNode.eachLevel(0,b.levelsToShow,
function(c){b.multitree&&!("$orn"in c.data)&&c.anySubnode(function(a){return a.exist&&!a.drawn})?a.push(c):c.drawn&&!c.anySubnode("drawn")&&a.push(c)});return a},w=[],p=new i({Implements:[{construct:function(a){var b="array"==f.type(a),c=new l(this.graphOptions,this.config.Node,this.config.Edge,this.config.Label);if(b)for(var b=function(b){for(var d=0,e=a.length;d<e;d++)if(a[d].id==b)return a[d];return c.addNode({id:b,name:b})},d=0,e=a.length;d<e;d++){c.addNode(a[d]);var g=a[d].adjacencies;if(g)for(var h=
0,j=g.length;h<j;h++){var k=g[h],i={};"string"!=typeof g[h]&&(i=f.merge(k.data,{}),k=k.nodeTo);c.addAdjacence(a[d],b(k),i)}}else(function(a,b){a.addNode(b);if(b.children)for(var c=0,d=b.children;c<d.length;c++)a.addAdjacence(b,d[c]),arguments.callee(a,d[c])})(c,a);return c},loadJSON:function(a,b){this.json=a;this.labels&&this.labels.clearLabels&&this.labels.clearLabels(!0);this.graph=this.construct(a);this.root="array"!=f.type(a)?a.id:a[b?b:0].id},toJSON:function(a){if("tree"==(a||"tree"))var b={},
b=function e(a){var b={};b.id=a.id;b.name=a.name;b.data=a.data;var c=[];a.eachSubnode(function(a){c.push(e(a))});b.children=c;return b}(this.graph.getNode(this.root));else{var b=[],c=!!this.graph.getNode(this.root).visited;this.graph.eachNode(function(a){var g={};g.id=a.id;g.name=a.name;g.data=a.data;var f=[];a.eachAdjacency(function(a){var b=a.nodeTo;if(!!b.visited===c){var e={};e.nodeTo=b.id;e.data=a.data;f.push(e)}});g.adjacencies=f;b.push(g);a.visited=!c})}return b}},y,p.Tree],initialize:function(a){var b=
$jit.ST,a=this.controller=this.config=f.merge(o("Canvas","Fx","Tree","Node","Edge","Controller","Tips","NodeStyles","Events","Navigation","Label"),{levelsToShow:2,levelDistance:30,constrained:!0,Node:{type:"rectangle"},duration:700,offsetX:0,offsetY:0},a);a.useCanvas?(this.canvas=a.useCanvas,this.config.labelContainer=this.canvas.id+"-label"):(a.background&&(a.background=f.merge({type:"Circles"},a.background)),this.canvas=new u(this,a),this.config.labelContainer=("string"==typeof a.injectInto?a.injectInto:
a.injectInto.id)+"-label");this.graphOptions={klass:n};this.graph=new l(this.graphOptions,this.config.Node,this.config.Edge);this.labels=new b.Label[a.Label.type](this);this.fx=new b.Plot(this,b);this.op=new b.Op(this);this.group=new b.Group(this);this.geom=new b.Geom(this);this.clickedNode=null;this.initializeExtras()},plot:function(){this.fx.plot(this.controller)},switchPosition:function(a,b,c){var d=this.geom,e=this.fx,g=this;e.busy||(e.busy=!0,this.contract({onComplete:function(){d.switchOrientation(a);
g.compute("end",!1);e.busy=!1;if("animate"==b)g.onClick(g.clickedNode.id,c);else"replot"==b&&g.select(g.clickedNode.id,c)}},a))},switchAlignment:function(a,b,c){this.config.align=a;if("animate"==b)this.select(this.clickedNode.id,c);else if("replot"==b)this.onClick(this.clickedNode.id,c)},addNodeInPath:function(a){w.push(a);this.select(this.clickedNode&&this.clickedNode.id||this.root)},clearNodesInPath:function(){w.length=0;this.select(this.clickedNode&&this.clickedNode.id||this.root)},refresh:function(){this.reposition();
this.select(this.clickedNode&&this.clickedNode.id||this.root)},reposition:function(){this.graph.computeLevels(this.root,0,"ignore");this.geom.setRightLevelToShow(this.clickedNode,this.canvas);this.graph.eachNode(function(a){a.exist&&(a.drawn=!0)});this.compute("end")},requestNodes:function(a,b){var c=f.merge(this.controller,b),d=this.config.levelsToShow;if(c.request){var e=[],g=a._depth;a.eachLevel(0,d,function(a){a.drawn&&!a.anySubnode()&&(e.push(a),a._level=d-(a._depth-g))});this.group.requestNodes(e,
c)}else c.onComplete()},contract:function(a,b){var c=this.config.orientation,d=this.geom,e=this.group;b&&d.switchOrientation(b);var g=T.call(this);b&&d.switchOrientation(c);e.contract(g,f.merge(this.controller,a))},move:function(a,b){this.compute("end",!1);var c=b.Move,d={x:c.offsetX,y:c.offsetY};c.enable&&this.geom.translate(a.endPos.add(d).$scale(-1),"end");this.fx.animate(f.merge(this.controller,{modes:["linear"]},b))},expand:function(a,b){var c=U.call(this,a);this.group.expand(c,f.merge(this.controller,
b))},selectPath:function(a){function b(a){null==a||a.selected||(a.selected=!0,f.each(c.group.getSiblings([a])[a.id],function(a){a.exist=!0;a.drawn=!0}),a=a.getParents(),a=0<a.length?a[0]:null,b(a))}var c=this;this.graph.eachNode(function(a){a.selected=!1});for(var d=0,a=[a.id].concat(w);d<a.length;d++)b(this.graph.getNode(a[d]))},setRoot:function(a,b,c){function d(){if(this.config.multitree&&j.data.$orn){var b={left:"right",right:"left",top:"bottom",bottom:"top"}[j.data.$orn];f.data.$orn=b;(function D(c){c.eachSubnode(function(c){c.id!=
a&&(c.data.$orn=b,D(c))})})(f);delete j.data.$orn}this.root=a;this.clickedNode=j;this.graph.computeLevels(this.root,0,"ignore");this.geom.setRightLevelToShow(j,g,{execHide:!1,onShow:function(a){a.drawn||(a.drawn=!0,a.setData("alpha",1,"end"),a.setData("alpha",0),a.pos.setc(j.pos.x,j.pos.y))}});this.compute("end");this.busy=!0;this.fx.animate({modes:["linear","node-property:alpha"],onComplete:function(){e.busy=!1;e.onClick(a,{onComplete:function(){c&&c.onComplete()}})}})}if(!this.busy){this.busy=!0;
var e=this,g=this.canvas,f=this.graph.getNode(this.root),j=this.graph.getNode(a);delete f.data.$orns;"animate"==b?(d.call(this),e.selectPath(j)):"replot"==b&&(d.call(this),this.select(this.root))}},addSubtree:function(a,b,c){"replot"==b?this.op.sum(a,f.extend({type:"replot"},c||{})):"animate"==b&&this.op.sum(a,f.extend({type:"fade:seq"},c||{}))},removeSubtree:function(a,b,c,d){var e=[];this.graph.getNode(a).eachLevel(+!b,!1,function(a){e.push(a.id)});"replot"==c?this.op.removeNode(e,f.extend({type:"replot"},
d||{})):"animate"==c&&this.op.removeNode(e,f.extend({type:"fade:seq"},d||{}))},select:function(a,b){var c=this.group,d=this.geom,e=this.graph.getNode(a),g=this.canvas;this.graph.getNode(this.root);var h=f.merge(this.controller,b),j=this;h.onBeforeCompute(e);this.selectPath(e);this.clickedNode=e;this.requestNodes(e,{onComplete:function(){c.hide(c.prepare(T.call(j)),h);d.setRightLevelToShow(e,g);j.compute("current");j.graph.eachNode(function(a){var b=a.pos.getc(!0);a.startPos.setc(b.x,b.y);a.endPos.setc(b.x,
b.y);a.visited=!1});j.geom.translate(e.endPos.add({x:h.offsetX,y:h.offsetY}).$scale(-1),["start","current","end"]);c.show(U.call(j));j.plot();h.onAfterCompute(j.clickedNode);h.onComplete()}})},onClick:function(a,b){var c=this.canvas,d=this,e=this.geom,g=this.config,h=f.merge(this.controller,{Move:{enable:!0,offsetX:g.offsetX||0,offsetY:g.offsetY||0},setRightLevelToShowConfig:!1,onBeforeRequest:f.empty,onBeforeContract:f.empty,onBeforeMove:f.empty,onBeforeExpand:f.empty},b);if(!this.busy){this.busy=
!0;var j=this.graph.getNode(a);this.selectPath(j,this.clickedNode);this.clickedNode=j;h.onBeforeCompute(j);h.onBeforeRequest(j);this.requestNodes(j,{onComplete:function(){h.onBeforeContract(j);d.contract({onComplete:function(){e.setRightLevelToShow(j,c,h.setRightLevelToShowConfig);h.onBeforeMove(j);d.move(j,{Move:h.Move,onComplete:function(){h.onBeforeExpand(j);d.expand(j,{onComplete:function(){d.busy=!1;h.onAfterCompute(a);h.onComplete()}})}})}})}})}}});q.ST=p;$jit.ST.$extend=!0;$jit.ST.Op=new i({Implements:l.Op});
$jit.ST.Group=new i({initialize:function(a){this.viz=a;this.canvas=a.canvas;this.config=a.config;this.animation=new C;this.nodes=null},requestNodes:function(a,b){var c=0,d=a.length,e=this.viz;if(0==d)b.onComplete();for(var g=0;g<d;g++)b.request(a[g].id,a[g]._level,{onComplete:function(a,g){g&&g.children&&(g.id=a,e.op.sum(g,{type:"nothing"}));++c==d&&(e.graph.computeLevels(e.root,0),b.onComplete())}})},contract:function(a,b){var c=this,a=this.prepare(a);this.animation.setOptions(f.merge(b,{$animating:!1,
compute:function(a){1==a&&(a=0.99);c.plotStep(1-a,b,this.$animating);this.$animating="contract"},complete:function(){c.hide(a,b)}})).start()},hide:function(a,b){for(var c=0;c<a.length;c++)a[c].eachLevel(1,!1,function(a){a.exist&&f.extend(a,{drawn:false,exist:false})});b.onComplete()},expand:function(a,b){var c=this;this.show(a);this.animation.setOptions(f.merge(b,{$animating:!1,compute:function(a){c.plotStep(a,b,this.$animating);this.$animating="expand"},complete:function(){c.plotStep(void 0,b,!1);
b.onComplete()}})).start()},show:function(a){var b=this.config;this.prepare(a);f.each(a,function(a){if(b.multitree&&!("$orn"in a.data)){delete a.data.$orns;var d=" ";a.eachSubnode(function(a){"$orn"in a.data&&(0>d.indexOf(a.data.$orn)&&a.exist&&!a.drawn)&&(d+=a.data.$orn+" ")});a.data.$orns=d}a.eachLevel(0,b.levelsToShow,function(a){a.exist&&(a.drawn=!0)})})},prepare:function(a){return this.nodes=this.getNodesWithChildren(a)},getNodesWithChildren:function(a){var b=[],c=this.config;a.sort(function(a,
b){return(a._depth<=b._depth)-(a._depth>=b._depth)});for(var d=0;d<a.length;d++)if(a[d].anySubnode("exist")){for(var e=d+1,g=!1;!g&&e<a.length;e++)if(!c.multitree||"$orn"in a[e].data)g=g||a[d].isDescendantOf(a[e].id);g||b.push(a[d])}return b},plotStep:function(a,b,c){var d=this.viz,e=this.config,g=d.canvas.getCtx(),h=this.nodes,j,k,i={};for(j=0;j<h.length;j++){k=h[j];i[k.id]=[];var l=e.multitree&&!("$orn"in k.data),n=l&&k.data.$orns;k.eachSubgraph(function(a){if(l&&n&&0<n.indexOf(a.data.$orn)&&a.drawn)a.drawn=
!1,i[k.id].push(a);else if((!l||!n)&&a.drawn)a.drawn=!1,i[k.id].push(a)});k.drawn=!0}0<h.length&&d.fx.plot();for(j in i)f.each(i[j],function(a){a.drawn=!0});for(j=0;j<h.length;j++)k=h[j],g.save(),d.fx.plotSubtree(k,b,a,c),g.restore()},getSiblings:function(a){var b={};f.each(a,function(a){var d=a.getParents();if(0==d.length)b[a.id]=[a];else{var e=[];d[0].eachSubnode(function(a){e.push(a)});b[a.id]=e}});return b}});$jit.ST.Geom=new i({Implements:l.Geom,switchOrientation:function(a){this.config.orientation=
a},dispatch:function(){var a=Array.prototype.slice.call(arguments),b=a.shift(),c=a.length,d=function(a){return"function"==typeof a?a():a};if(2==c)return"top"==b||"bottom"==b?d(a[0]):d(a[1]);if(4==c)switch(b){case "top":return d(a[0]);case "right":return d(a[1]);case "bottom":return d(a[2]);case "left":return d(a[3])}},getSize:function(a,b){var c=a.data,d=this.config,e=d.siblingOffset,c=d.multitree&&"$orn"in c&&c.$orn||d.orientation,d=a.getData("width")+e,e=a.getData("height")+e;return b?this.dispatch(c,
d,e):this.dispatch(c,e,d)},getTreeBaseSize:function(a,b,c){var d=this.getSize(a,!0),e=0,g=this;if(c(b,a))return d;if(0===b)return 0;a.eachSubnode(function(a){e+=g.getTreeBaseSize(a,b-1,c)});return(d>e?d:e)+this.config.subtreeOffset},getEdge:function(a,b,c){var d=function(b,c){return function(){return a.pos.add(new n(b,c))}},e=this.node,g=a.getData("width"),f=a.getData("height");if("begin"==b){if("center"==e.align)return this.dispatch(c,d(0,f/2),d(-g/2,0),d(0,-f/2),d(g/2,0));if("left"==e.align)return this.dispatch(c,
d(0,f),d(0,0),d(0,0),d(g,0));if("right"==e.align)return this.dispatch(c,d(0,0),d(-g,0),d(0,-f),d(0,0));throw"align: not implemented";}if("end"==b){if("center"==e.align)return this.dispatch(c,d(0,-f/2),d(g/2,0),d(0,f/2),d(-g/2,0));if("left"==e.align)return this.dispatch(c,d(0,0),d(g,0),d(0,f),d(0,0));if("right"==e.align)return this.dispatch(c,d(0,-f),d(0,0),d(0,0),d(-g,0));throw"align: not implemented";}},getScaledTreePosition:function(a,b){var c=this.node,d=a.getData("width"),e=a.getData("height"),
g=this.config.multitree&&"$orn"in a.data&&a.data.$orn||this.config.orientation,f=function(c,d){return function(){return a.pos.add(new n(c,d)).$scale(1-b)}};if("left"==c.align)return this.dispatch(g,f(0,e),f(0,0),f(0,0),f(d,0));if("center"==c.align)return this.dispatch(g,f(0,e/2),f(-d/2,0),f(0,-e/2),f(d/2,0));if("right"==c.align)return this.dispatch(g,f(0,0),f(-d,0),f(0,-e),f(0,0));throw"align: not implemented";},treeFitsInCanvas:function(a,b,c){b=b.getSize();b=this.dispatch(this.config.multitree&&
"$orn"in a.data&&a.data.$orn||this.config.orientation,b.width,b.height);return this.getTreeBaseSize(a,c,function(a,b){return 0===a||!b.anySubnode()})<b}});$jit.ST.Plot=new i({Implements:l.Plot,plotSubtree:function(a,b,c,d){var e=this.viz,g=e.canvas,h=e.config,c=Math.min(Math.max(0.001,c),1);0<=c&&(a.drawn=!1,g=g.getCtx(),e=e.geom.getScaledTreePosition(a,c),g.translate(e.x,e.y),g.scale(c,c));this.plotTree(a,f.merge(b,{withLabels:!0,hideLabels:!!c,plotSubtree:function(){var b=h.multitree&&!("$orn"in
a.data),c=b&&a.getData("orns");return!b||c.indexOf(a.getData("orn"))>-1}}),d);0<=c&&(a.drawn=!0)},getAlignedPos:function(a,b,c){var d=this.node;if("center"==d.align)a={x:a.x-b/2,y:a.y-c/2};else if("left"==d.align)d=this.config.orientation,a="bottom"==d||"top"==d?{x:a.x-b/2,y:a.y}:{x:a.x,y:a.y-c/2};else if("right"==d.align)d=this.config.orientation,a="bottom"==d||"top"==d?{x:a.x-b/2,y:a.y-c}:{x:a.x-b,y:a.y-c/2};else throw"align: not implemented";return a},getOrientation:function(a){var b=this.config,
c=b.orientation;b.multitree&&(b=a.nodeFrom,a=a.nodeTo,c="$orn"in b.data&&b.data.$orn||"$orn"in a.data&&a.data.$orn);return c}});$jit.ST.Label={};$jit.ST.Label.Native=new i({Implements:l.Label.Native,renderLabel:function(a,b){var c=a.getCtx(),d=b.pos.getc(!0),e=b.getData("width"),g=b.getData("height"),d=this.viz.fx.getAlignedPos(d,e,g);c.fillText(b.name,d.x+e/2,d.y+g/2)}});$jit.ST.Label.DOM=new i({Implements:l.Label.DOM,placeLabel:function(a,b,c){var d=b.pos.getc(!0),e=this.viz.config,g=e.Node,f=this.viz.canvas,
j=b.getData("width"),k=b.getData("height"),i=f.getSize(),l=d.x*f.scaleOffsetX+f.translateOffsetX,d=d.y*f.scaleOffsetY+f.translateOffsetY;if("center"==g.align)j={x:Math.round(l-j/2+i.width/2),y:Math.round(d-k/2+i.height/2)};else if("left"==g.align)e=e.orientation,j="bottom"==e||"top"==e?{x:Math.round(l-j/2+i.width/2),y:Math.round(d+i.height/2)}:{x:Math.round(l+i.width/2),y:Math.round(d-k/2+i.height/2)};else if("right"==g.align)e=e.orientation,j="bottom"==e||"top"==e?{x:Math.round(l-j/2+i.width/2),
y:Math.round(d-k+i.height/2)}:{x:Math.round(l-j+i.width/2),y:Math.round(d-k/2+i.height/2)};else throw"align: not implemented";k=a.style;k.left=j.x+"px";k.top=j.y+"px";k.display=this.fitsInCanvas(j,f)?"":"none";c.onPlaceLabel(a,b)}});$jit.ST.Label.SVG=new i({Implements:[$jit.ST.Label.DOM,l.Label.SVG],initialize:function(a){this.viz=a}});$jit.ST.Label.HTML=new i({Implements:[$jit.ST.Label.DOM,l.Label.HTML],initialize:function(a){this.viz=a}});$jit.ST.Plot.NodeTypes=new i({none:{render:f.empty,contains:f.lambda(!1)},
circle:{render:function(a,b){var c=a.getData("dim"),d=this.getAlignedPos(a.pos.getc(!0),c,c),c=c/2;this.nodeHelper.circle.render("fill",{x:d.x+c,y:d.y+c},c,b)},contains:function(a,b){var c=a.getData("dim"),d=this.getAlignedPos(a.pos.getc(!0),c,c),c=c/2;this.nodeHelper.circle.contains({x:d.x+c,y:d.y+c},b,c)}},square:{render:function(a,b){var c=a.getData("dim"),d=c/2,c=this.getAlignedPos(a.pos.getc(!0),c,c);this.nodeHelper.square.render("fill",{x:c.x+d,y:c.y+d},d,b)},contains:function(a,b){var c=a.getData("dim"),
d=this.getAlignedPos(a.pos.getc(!0),c,c),c=c/2;this.nodeHelper.square.contains({x:d.x+c,y:d.y+c},b,c)}},ellipse:{render:function(a,b){var c=a.getData("width"),d=a.getData("height"),e=this.getAlignedPos(a.pos.getc(!0),c,d);this.nodeHelper.ellipse.render("fill",{x:e.x+c/2,y:e.y+d/2},c,d,b)},contains:function(a,b){var c=a.getData("width"),d=a.getData("height"),e=this.getAlignedPos(a.pos.getc(!0),c,d);this.nodeHelper.ellipse.contains({x:e.x+c/2,y:e.y+d/2},b,c,d)}},rectangle:{render:function(a,b){var c=
a.getData("width"),d=a.getData("height"),e=this.getAlignedPos(a.pos.getc(!0),c,d);this.nodeHelper.rectangle.render("fill",{x:e.x+c/2,y:e.y+d/2},c,d,b)},contains:function(a,b){var c=a.getData("width"),d=a.getData("height"),e=this.getAlignedPos(a.pos.getc(!0),c,d);this.nodeHelper.rectangle.contains({x:e.x+c/2,y:e.y+d/2},b,c,d)}}});$jit.ST.Plot.EdgeTypes=new i({none:f.empty,line:{render:function(a,b){var c=this.getOrientation(a),d=a.nodeFrom,e=a.nodeTo,g=d._depth<e._depth,f=this.viz.geom.getEdge(g?d:
e,"begin",c),c=this.viz.geom.getEdge(g?e:d,"end",c);this.edgeHelper.line.render(f,c,b)},contains:function(a,b){var c=this.getOrientation(a),d=a.nodeFrom,e=a.nodeTo,g=d._depth<e._depth,f=this.viz.geom.getEdge(g?d:e,"begin",c),c=this.viz.geom.getEdge(g?e:d,"end",c);return this.edgeHelper.line.contains(f,c,b,this.edge.epsilon)}},arrow:{render:function(a,b){var c=this.getOrientation(a),d=a.nodeFrom,e=a.nodeTo,g=a.getData("dim"),f=this.viz.geom.getEdge(d,"begin",c),c=this.viz.geom.getEdge(e,"end",c),e=
a.data.$direction;this.edgeHelper.arrow.render(f,c,g,e&&1<e.length&&e[0]!=d.id,b)},contains:function(a,b){var c=this.getOrientation(a),d=a.nodeFrom,e=a.nodeTo,g=d._depth<e._depth,f=this.viz.geom.getEdge(g?d:e,"begin",c),c=this.viz.geom.getEdge(g?e:d,"end",c);return this.edgeHelper.arrow.contains(f,c,b,this.edge.epsilon)}},"quadratic:begin":{render:function(a,b){var c=this.getOrientation(a),d=a.nodeFrom,e=a.nodeTo,g=d._depth<e._depth,f=this.viz.geom.getEdge(g?d:e,"begin",c),d=this.viz.geom.getEdge(g?
e:d,"end",c),e=a.getData("dim"),g=b.getCtx();g.beginPath();g.moveTo(f.x,f.y);switch(c){case "left":g.quadraticCurveTo(f.x+e,f.y,d.x,d.y);break;case "right":g.quadraticCurveTo(f.x-e,f.y,d.x,d.y);break;case "top":g.quadraticCurveTo(f.x,f.y+e,d.x,d.y);break;case "bottom":g.quadraticCurveTo(f.x,f.y-e,d.x,d.y)}g.stroke()}},"quadratic:end":{render:function(a,b){var c=this.getOrientation(a),d=a.nodeFrom,e=a.nodeTo,f=d._depth<e._depth,h=this.viz.geom.getEdge(f?d:e,"begin",c),d=this.viz.geom.getEdge(f?e:d,
"end",c),e=a.getData("dim"),f=b.getCtx();f.beginPath();f.moveTo(h.x,h.y);switch(c){case "left":f.quadraticCurveTo(d.x-e,d.y,d.x,d.y);break;case "right":f.quadraticCurveTo(d.x+e,d.y,d.x,d.y);break;case "top":f.quadraticCurveTo(d.x,d.y-e,d.x,d.y);break;case "bottom":f.quadraticCurveTo(d.x,d.y+e,d.x,d.y)}f.stroke()}},bezier:{render:function(a,b){var c=this.getOrientation(a),d=a.nodeFrom,e=a.nodeTo,f=d._depth<e._depth,h=this.viz.geom.getEdge(f?d:e,"begin",c),d=this.viz.geom.getEdge(f?e:d,"end",c),e=a.getData("dim"),
f=b.getCtx();f.beginPath();f.moveTo(h.x,h.y);switch(c){case "left":f.bezierCurveTo(h.x+e,h.y,d.x-e,d.y,d.x,d.y);break;case "right":f.bezierCurveTo(h.x-e,h.y,d.x+e,d.y,d.x,d.y);break;case "top":f.bezierCurveTo(h.x,h.y+e,d.x,d.y-e,d.x,d.y);break;case "bottom":f.bezierCurveTo(h.x,h.y-e,d.x,d.y+e,d.x,d.y)}f.stroke()}}})})();
