/*
 * Copyright 2013 Corpuslinguistic working group Humboldt University Berlin.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package annis.gui;

import annis.gui.controlpanel.CorpusListPanel;
import annis.service.objects.AnnisCorpus;
import com.vaadin.ui.Accordion;
import com.vaadin.ui.Component;
import java.util.List;

/**
 *
 * @author Benjamin Weißenfels <b.pixeldrama@gmail.com>
 */
public class AutoGenQueriesPanel extends Accordion
{

  private final SearchUI ui;

  private List<AnnisCorpus> allCorpora;

  public AutoGenQueriesPanel(SearchUI ui)
  {
    super();
    this.ui = ui;
  }

  @Override
  public void attach()
  {
    super.attach();
  }

  /**
   * Reads the corpora from the {@link CorpusListPanel}.
   */
  public void addCorpora(List<AnnisCorpus> allCorpora)
  {
    this.allCorpora = allCorpora;
    initExampleQueries(allCorpora);
  }

  /**
   * Puts all corpora into the accordian panel
   *
   * @param allCorpora
   */
  private void initExampleQueries(List<AnnisCorpus> allCorpora)
  {
    for (AnnisCorpus c : allCorpora)
    {
      AutoGeneratedQueries autoGenQ = new AutoGeneratedQueries(c.getName(), ui);
      addComponent(autoGenQ);
    }
  }
}
