/*
 * graphANNIS
 * Access the graphANNIS corpora and execute AQL queries with this service. 
 *
 * OpenAPI spec version: 0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.corpus_tools.annis;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.corpus_tools.annis.AnnotationComponentType;
/**
 * Definition of an edge component
 */
@Schema(description = "Definition of an edge component")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-06-24T14:51:23.486442+02:00[Europe/Berlin]")
public class Component {
  @SerializedName("type")
  private AnnotationComponentType type = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("layer")
  private String layer = null;

  public Component type(AnnotationComponentType type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(description = "")
  public AnnotationComponentType getType() {
    return type;
  }

  public void setType(AnnotationComponentType type) {
    this.type = type;
  }

  public Component name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the component
   * @return name
  **/
  @Schema(example = "dep", description = "Name of the component")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Component layer(String layer) {
    this.layer = layer;
    return this;
  }

   /**
   * A layer name which allows to group different components into the same layer. Can be the empty string.
   * @return layer
  **/
  @Schema(example = "conll", description = "A layer name which allows to group different components into the same layer. Can be the empty string.")
  public String getLayer() {
    return layer;
  }

  public void setLayer(String layer) {
    this.layer = layer;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Component component = (Component) o;
    return Objects.equals(this.type, component.type) &&
        Objects.equals(this.name, component.name) &&
        Objects.equals(this.layer, component.layer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, name, layer);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Component {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    layer: ").append(toIndentedString(layer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
