/*
 * graphANNIS
 * Access the graphANNIS corpora and execute AQL queries with this service. 
 *
 * OpenAPI spec version: 0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.corpus_tools.annis;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Configuration how the results of a query should be shown
 */
@Schema(description = "Configuration how the results of a query should be shown")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-06-26T15:55:16.485632+02:00[Europe/Berlin]")
public class CorpusConfigurationView {
  @SerializedName("base_text_segmentation")
  private String baseTextSegmentation = null;

  @SerializedName("page_size")
  private Integer pageSize = null;

  public CorpusConfigurationView baseTextSegmentation(String baseTextSegmentation) {
    this.baseTextSegmentation = baseTextSegmentation;
    return this;
  }

   /**
   * Default segmentation to use for the displaying the text, Set to null or omit it if tokens should be used.
   * @return baseTextSegmentation
  **/
  @Schema(example = "dipl", description = "Default segmentation to use for the displaying the text, Set to null or omit it if tokens should be used.")
  public String getBaseTextSegmentation() {
    return baseTextSegmentation;
  }

  public void setBaseTextSegmentation(String baseTextSegmentation) {
    this.baseTextSegmentation = baseTextSegmentation;
  }

  public CorpusConfigurationView pageSize(Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

   /**
   * Default number of results to show at once for paginated queries.
   * @return pageSize
  **/
  @Schema(example = "10", description = "Default number of results to show at once for paginated queries.")
  public Integer getPageSize() {
    return pageSize;
  }

  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CorpusConfigurationView corpusConfigurationView = (CorpusConfigurationView) o;
    return Objects.equals(this.baseTextSegmentation, corpusConfigurationView.baseTextSegmentation) &&
        Objects.equals(this.pageSize, corpusConfigurationView.pageSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(baseTextSegmentation, pageSize);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CorpusConfigurationView {\n");
    
    sb.append("    baseTextSegmentation: ").append(toIndentedString(baseTextSegmentation)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
