CREATE INDEX idx_corpus__pre_post ON corpus USING btree (pre, post);
CREATE INDEX fk_doc_2_corpus ON doc_2_corp USING btree (corpus_ref);
CREATE INDEX idx_s__doc_ref__istoken ON struct USING btree (doc_ref) WHERE (token_index IS NOT NULL);
CREATE INDEX fk_struct_2_text ON struct USING btree (text_ref);
CREATE INDEX idx_struct__token_index ON struct USING btree (token_index);
CREATE INDEX fk_rank_2_rank ON rank USING btree (parent);
CREATE INDEX fk_rank_2_struct ON rank USING btree (struct_ref);
CREATE INDEX idx_rank__pre ON rank USING btree (pre);
CREATE INDEX fk_rank_anno_2_rank ON rank_anno USING btree (rank_ref);
CREATE INDEX idx_rank_anno__value ON rank_anno USING btree (value);
CREATE INDEX idx_annotation__ns_attribute_not_null ON annotation USING btree (ns, attribute) WHERE (attribute IS NOT NULL);
CREATE INDEX fk_annotation_2_struct ON annotation USING btree (struct_ref);
CREATE INDEX idx_s_a__doc_ref_ns_attribute_not_null_value ON struct_annotation USING btree (doc_ref, ns, attribute, value) WHERE (attribute IS NOT NULL);
CREATE INDEX idx_s_a__text_ref_left_token_minus_1_right_token_value ON struct_annotation USING btree (text_ref, ((left_token - 1)), right_token, value);
CREATE INDEX idx_s_a__id_text_ref_left ON struct_annotation USING btree (id, text_ref, "left");
CREATE INDEX idx_s_a__id_text_ref_left_token_right_token ON struct_annotation USING btree (id, text_ref, left_token, right_token);
CREATE INDEX idx_s_a__left_text_ref ON struct_annotation USING btree ("left", text_ref);
CREATE INDEX idx_s_a__text_ref_left_token_minus_1_right_token ON struct_annotation USING btree (text_ref, ((left_token - 1)), right_token);
CREATE INDEX idx_s_a__id_value_attribute ON struct_annotation USING btree (id, value, attribute);
CREATE INDEX idx_s_a__attribute_value_id ON struct_annotation USING btree (attribute, value, id);
CREATE INDEX idx_s_a__value_attribute ON struct_annotation USING btree (value, attribute);
CREATE INDEX idx_s_a__attribute ON struct_annotation USING btree (attribute);
CREATE INDEX idx_s_a__span ON struct_annotation USING btree (span);
CREATE INDEX fk_struct_annotation_2_text ON struct_annotation USING btree (text_ref);
CREATE INDEX idx_s_a__id ON struct_annotation USING btree (id);
CREATE INDEX idx_r_a__pre_post ON rank_annotation USING btree (pre, post);
CREATE INDEX idx_r_t_r__level_text_ref_pre_post ON rank_text_ref USING btree (level, text_ref, pre, post);
CREATE INDEX idx_rank__parent_zshg ON rank (parent, zshg);
CREATE INDEX idx_rank__edge_type ON rank (edge_type);