/*
 * graphANNIS
 * Access the graphANNIS corpora and execute AQL queries with this service. 
 *
 * The version of the OpenAPI document: 0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.corpus_tools.annis.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.corpus_tools.annis.api.model.FrequencyQueryDefinition;
import org.corpus_tools.annis.api.model.QueryLanguage;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FrequencyQuery
 */
public class FrequencyQueryTest {
    private final FrequencyQuery model = new FrequencyQuery();

    /**
     * Model tests for FrequencyQuery
     */
    @Test
    public void testFrequencyQuery() {
        // TODO: test FrequencyQuery
    }

    /**
     * Test the property 'query'
     */
    @Test
    public void queryTest() {
        // TODO: test query
    }

    /**
     * Test the property 'queryLanguage'
     */
    @Test
    public void queryLanguageTest() {
        // TODO: test queryLanguage
    }

    /**
     * Test the property 'corpora'
     */
    @Test
    public void corporaTest() {
        // TODO: test corpora
    }

    /**
     * Test the property 'definition'
     */
    @Test
    public void definitionTest() {
        // TODO: test definition
    }

}
