/*
 * graphANNIS
 * Access the graphANNIS corpora and execute AQL queries with this service. 
 *
 * The version of the OpenAPI document: 0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.corpus_tools.annis.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for LineColumn
 */
public class LineColumnTest {
    private final LineColumn model = new LineColumn();

    /**
     * Model tests for LineColumn
     */
    @Test
    public void testLineColumn() {
        // TODO: test LineColumn
    }

    /**
     * Test the property 'line'
     */
    @Test
    public void lineTest() {
        // TODO: test line
    }

    /**
     * Test the property 'column'
     */
    @Test
    public void columnTest() {
        // TODO: test column
    }

}
