/*
 * graphANNIS
 * Access the graphANNIS corpora and execute AQL queries with this service. 
 *
 * The version of the OpenAPI document: 0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.corpus_tools.annis.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for QueryAttributeDescription
 */
public class QueryAttributeDescriptionTest {
    private final QueryAttributeDescription model = new QueryAttributeDescription();

    /**
     * Model tests for QueryAttributeDescription
     */
    @Test
    public void testQueryAttributeDescription() {
        // TODO: test QueryAttributeDescription
    }

    /**
     * Test the property 'alternative'
     */
    @Test
    public void alternativeTest() {
        // TODO: test alternative
    }

    /**
     * Test the property 'queryFragment'
     */
    @Test
    public void queryFragmentTest() {
        // TODO: test queryFragment
    }

    /**
     * Test the property 'variable'
     */
    @Test
    public void variableTest() {
        // TODO: test variable
    }

    /**
     * Test the property 'annoName'
     */
    @Test
    public void annoNameTest() {
        // TODO: test annoName
    }

}
