/*
 * graphANNIS
 * Access the graphANNIS corpora and execute AQL queries with this service. 
 *
 * The version of the OpenAPI document: 0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.corpus_tools.annis.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SubgraphWithContext
 */
public class SubgraphWithContextTest {
    private final SubgraphWithContext model = new SubgraphWithContext();

    /**
     * Model tests for SubgraphWithContext
     */
    @Test
    public void testSubgraphWithContext() {
        // TODO: test SubgraphWithContext
    }

    /**
     * Test the property 'nodeIds'
     */
    @Test
    public void nodeIdsTest() {
        // TODO: test nodeIds
    }

    /**
     * Test the property 'segmentation'
     */
    @Test
    public void segmentationTest() {
        // TODO: test segmentation
    }

    /**
     * Test the property 'left'
     */
    @Test
    public void leftTest() {
        // TODO: test left
    }

    /**
     * Test the property 'right'
     */
    @Test
    public void rightTest() {
        // TODO: test right
    }

}
