<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="graph"
    nsURI="www.corpling.de/util/graph" nsPrefix="graph">
  <eClassifiers xsi:type="ecore:EClass" name="IdentifiableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Graph" eSuperTypes="#//IdentifiableElement #//LabelableElement #//IndexMgr #//TraversalObject">
    <eOperations name="addNode">
      <eParameters name="node" eType="#//Node"/>
    </eOperations>
    <eOperations name="getNode" eType="#//Node">
      <eParameters name="nodeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="removeNodeById" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="nodeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="removeNodes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="addEdge">
      <eParameters name="edge" eType="#//Edge"/>
    </eOperations>
    <eOperations name="getEdge" eType="#//Edge">
      <eParameters name="edgeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="getEdges" upperBound="-1" eType="#//Edge">
      <eParameters name="nodeId1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eParameters name="nodeId2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="getInEdges" upperBound="-1" eType="#//Edge">
      <eParameters name="nodeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="getOutEdges" upperBound="-1" eType="#//Edge">
      <eParameters name="nodeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="removeEdgeById" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="edgeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="removeEdges" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="traverseGraph">
      <eParameters name="traversalMode" eType="#//TRAVERSAL_MODE"/>
      <eParameters name="startNode" eType="#//Node"/>
      <eParameters name="traversalObject" eType="#//TraversalObject"/>
    </eOperations>
    <eOperations name="traverseGraph">
      <eParameters name="traversalMode" eType="#//TRAVERSAL_MODE"/>
      <eParameters name="startNodes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList"/>
      <eParameters name="traversalObject" eType="#//TraversalObject"/>
    </eOperations>
    <eOperations name="getRoots" upperBound="-1" eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node" unsettable="true" containment="true" eOpposite="#//Node/graph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1"
        eType="#//Edge" unsettable="true" containment="true" eOpposite="#//Edge/graph"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numOfNodes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numOfEdges" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="labelableElement" lowerBound="1"
        eType="#//LabelableElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexMgr" lowerBound="1"
        eType="#//IndexMgr" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//IdentifiableElement #//LabelableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="graph" lowerBound="1" eType="#//Graph"
        eOpposite="#//Graph/nodes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="labelableElement" lowerBound="1"
        eType="#//LabelableElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Edge" eSuperTypes="#//IdentifiableElement #//LabelableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" lowerBound="1"
        eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graph" lowerBound="1" eType="#//Graph"
        eOpposite="#//Graph/edges"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="labelableElement" lowerBound="1"
        eType="#//LabelableElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LabelableElement">
    <eOperations name="addLabel">
      <eParameters name="label" eType="#//Label"/>
    </eOperations>
    <eOperations name="getLabel" eType="#//Label">
      <eParameters name="fullName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getLabel" eType="#//Label">
      <eParameters name="namespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="removeLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="fullName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="removeLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="namespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="hasLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="fullName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="hasLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="namespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="removeAll" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="getLabelsByNamespace" upperBound="-1" eType="#//Label">
      <eParameters name="namespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="labels" upperBound="-1"
        eType="#//Label" containment="true" eOpposite="#//Label/labelOwner"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numOfLabels" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Label">
    <eOperations name="getNSSeperator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="labelOwner" lowerBound="1"
        eType="#//LabelableElement" eOpposite="#//LabelableElement/labels"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TRAVERSAL_MODE">
    <eLiterals name="DEPTH_FIRST"/>
    <eLiterals name="BOTTOM_UP" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TraversalObject" abstract="true" interface="true">
    <eOperations name="nodeReached">
      <eParameters name="traversalMode" eType="#//TRAVERSAL_MODE"/>
      <eParameters name="currNode" eType="#//Node"/>
      <eParameters name="edge" eType="#//Edge"/>
      <eParameters name="fromNode" eType="#//Node"/>
      <eParameters name="order" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eOperations>
    <eOperations name="nodeLeft">
      <eParameters name="traversalMode" eType="#//TRAVERSAL_MODE"/>
      <eParameters name="currNode" eType="#//Node"/>
      <eParameters name="edge" eType="#//Edge"/>
      <eParameters name="fromNode" eType="#//Node"/>
      <eParameters name="order" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eOperations>
    <eOperations name="checkConstraint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="traversalMode" eType="#//TRAVERSAL_MODE"/>
      <eParameters name="edge" eType="#//Edge"/>
      <eParameters name="currNode" eType="#//Node"/>
      <eParameters name="order" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Index" abstract="true" interface="true"
      eSuperTypes="#//IdentifiableElement">
    <eOperations name="addElement">
      <eParameters name="elementId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eParameters name="element" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="hasElement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="elementId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="removeElement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="elementId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="removeAll" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numOfElements" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong" changeable="false"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleIndex" eSuperTypes="#//Index">
    <eOperations name="getElement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
      <eParameters name="elementId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idxTable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndexMgr">
    <eOperations name="addIndex">
      <eParameters name="index" eType="#//Index"/>
    </eOperations>
    <eOperations name="hasIndex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="indexId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="getIndex" eType="#//Index">
      <eParameters name="indexId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="removeIndex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="indexId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="removeAll" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="removeElement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="element" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexes" upperBound="-1"
        eType="#//Index" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numOfIndexes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexIndex" eSuperTypes="#//Index">
    <eOperations name="hasSlot" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="slotId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="getSlot" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
      <eParameters name="slotId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="getSlotIds" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eOperations name="removeSlot" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="slotId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idxTable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numOfSlots" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong" changeable="false"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndexableElement"/>
</ecore:EPackage>
