<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="relANNIS"
    nsURI="relANNIS" nsPrefix="ra">
  <eClassifiers xsi:type="ecore:EClass" name="RAExporter" eSuperTypes="../../Peper/model/peper.ecore#//Exporter">
    <eOperations name="export">
      <eParameters name="sCorpus" eType="ecore:EClass Salt.ecore#//SCorpus"/>
    </eOperations>
    <eOperations name="export">
      <eParameters name="sDocument" eType="ecore:EClass Salt.ecore#//SDocument"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="raMapper" eType="#//RAMapper"
        eOpposite="#//RAMapper/raExporter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="raDAO" eType="#//RADAO"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="SaltProject" instanceClassName="de.corpling.salt.saltFW.SaltProject"/>
  <eClassifiers xsi:type="ecore:EDataType" name="File" instanceClassName="java.io.File"/>
  <eClassifiers xsi:type="ecore:EClass" name="RAMapper" eSuperTypes="SaltCore.ecore#//STraversalObject">
    <eOperations name="init">
      <eParameters name="document" eType="ecore:EClass Salt.ecore#//SDocument"/>
    </eOperations>
    <eOperations name="close"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="raDAO" eType="#//RADAO"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currTaId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="raExporter" eType="#//RAExporter"
        eOpposite="#//RAExporter/raMapper"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="coherentComponents" upperBound="-1"
        eType="#//SElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subConnectedComponents"
        upperBound="-1" eType="#//SElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RADAO" eSuperTypes="SaltCore.ecore#//STraversalObject">
    <eOperations name="write">
      <eParameters name="taId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
      <eParameters name="raCorpus" eType="#//RACorpus"/>
    </eOperations>
    <eOperations name="beginTA" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eOperations name="commitTA">
      <eParameters name="taId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eOperations>
    <eOperations name="addTupleWriter">
      <eParameters name="daoObject" eType="#//DAOOBJECT"/>
      <eParameters name="tupleWriter" eType="#//TupleWriter"/>
    </eOperations>
    <eOperations name="reSetTupleWriter">
      <eParameters name="daoObject" eType="#//DAOOBJECT"/>
      <eParameters name="tupleWriter" eType="#//TupleWriter"/>
    </eOperations>
    <eOperations name="getTupleWriter" eType="#//TupleWriter">
      <eParameters name="daoObject" eType="#//DAOOBJECT"/>
    </eOperations>
    <eOperations name="write">
      <eParameters name="taId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
      <eParameters name="raCorpusMetaAttribute" eType="#//RACorpusAnnotation"/>
    </eOperations>
    <eOperations name="getUniqueValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
      <eParameters name="uniqueValue" eType="#//UNIQUE_VALUES"/>
    </eOperations>
    <eOperations name="write">
      <eParameters name="taId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
      <eParameters name="raText" eType="#//RAText"/>
    </eOperations>
    <eOperations name="write">
      <eParameters name="taId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
      <eParameters name="raStruct" eType="#//RANode"/>
    </eOperations>
    <eOperations name="write">
      <eParameters name="taId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
      <eParameters name="raRank" eType="#//RAEdge"/>
    </eOperations>
    <eOperations name="write">
      <eParameters name="taId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
      <eParameters name="raAnno" eType="#//RANodeAnnotation"/>
    </eOperations>
    <eOperations name="write">
      <eParameters name="taId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
      <eParameters name="raRankType" eType="#//RAComponent"/>
    </eOperations>
    <eOperations name="write">
      <eParameters name="taId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
      <eParameters name="raEdgeAnnotation" eType="#//RAEdgeAnnotation"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputDir" eType="#//File"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tupleWriterEntries" upperBound="-1"
        eType="#//TupleWriterEntry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taEntries" upperBound="-1"
        eType="#//TaEntry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uniqueValues" upperBound="-1"
        eType="#//UniqueValueEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RACorpus">
    <eOperations name="toStringList" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//RA_CORPUS_TYPE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="post" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RA_CORPUS_TYPE">
    <eLiterals name="CORPUS"/>
    <eLiterals name="DOCUMENT" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EXPORT_FILE">
    <eLiterals name="CORPUS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="TupleWriter" instanceClassName="de.dataconnector.tupleconnector.ITupleWriter"/>
  <eClassifiers xsi:type="ecore:EClass" name="TupleWriterEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="#//DAOOBJECT"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//TupleWriterContainer"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DAOOBJECT">
    <eLiterals name="CORPUS"/>
    <eLiterals name="CORPUS_ANNOTATION" value="1"/>
    <eLiterals name="TEXT" value="2"/>
    <eLiterals name="NODE" value="3"/>
    <eLiterals name="EDGE" value="4"/>
    <eLiterals name="COMPONENT" value="5"/>
    <eLiterals name="EDGE_ANNOTATION" value="6"/>
    <eLiterals name="NODE_ANNOTATION" value="7"/>
    <eLiterals name="ANNOTATION_META_ATTRIBUTE" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TupleWriterContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tupleWriter" eType="#//TupleWriter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//TAObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TAObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="taId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="twWriterKey" eType="#//DAOOBJECT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RACorpusAnnotation">
    <eOperations name="toStringList" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="corpus_ref" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UNIQUE_VALUES">
    <eLiterals name="CORP_STRUCT_PPORDER"/>
    <eLiterals name="CORPUS_ID" value="1"/>
    <eLiterals name="TEXT_ID" value="2"/>
    <eLiterals name="STRUCT_ID" value="3"/>
    <eLiterals name="RANK_PPORDER" value="4"/>
    <eLiterals name="ANNO_ID" value="5"/>
    <eLiterals name="RANK_TYPE_ID" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UniqueValueEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//UniqueValue"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="#//UNIQUE_VALUES"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UniqueValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RAText">
    <eOperations name="toStringList" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RANode">
    <eOperations name="toStringList" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text_ref" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="corpus_ref" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="left" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="right" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="token_index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="continuous" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="span" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RAEdge">
    <eOperations name="toStringList" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="post" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="node_ref" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="component_ref" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RANodeAnnotation">
    <eOperations name="toStringList" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="node_ref" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="SElement" instanceClassName="de.corpling.salt.model.saltCore.SElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="RAComponent">
    <eOperations name="toStringList" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RAEdgeAnnotation">
    <eOperations name="toStringList" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="edge_ref" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
