/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.corpling.peper.modules.relANNIS.validation;

import de.corpling.peper.modules.relANNIS.RA_CORPUS_TYPE;

/**
 * A sample validator interface for {@link de.corpling.peper.modules.relANNIS.RACorpus}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RACorpusValidator {
	boolean validate();

	boolean validateId(Long value);
	boolean validateName(String value);
	boolean validateType(RA_CORPUS_TYPE value);
	boolean validateVersion(String value);
	boolean validatePre(Long value);
	boolean validatePost(Long value);
}
