/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.corpling.peper.modules.relANNIS.validation;

import de.corpling.peper.modules.relANNIS.DAOOBJECT;
import de.corpling.peper.modules.relANNIS.TAObject;
import de.corpling.peper.modules.relANNIS.TupleWriterContainer;
import de.corpling.peper.modules.relANNIS.UNIQUE_VALUES;
import de.corpling.peper.modules.relANNIS.UniqueValue;

import java.io.File;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.EMap;

/**
 * A sample validator interface for {@link de.corpling.peper.modules.relANNIS.RADAO}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RADAOValidator {
	boolean validate();

	boolean validateOutputDir(File value);
	boolean validateTupleWriterEntries(EMap<DAOOBJECT, TupleWriterContainer> value);
	boolean validateTaEntries(EMap<Long, EList<TAObject>> value);
	boolean validateUniqueValues(EMap<UNIQUE_VALUES, UniqueValue> value);
}
