/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.corpling.peper.modules.relANNIS.validation;


/**
 * A sample validator interface for {@link de.corpling.peper.modules.relANNIS.RAEdge}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RAEdgeValidator {
	boolean validate();

	boolean validatePre(Long value);
	boolean validatePost(Long value);
	boolean validateNode_ref(Long value);
	boolean validateComponent_ref(Long value);
	boolean validateParent(Long value);
}
