/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.corpling.peper.modules.relANNIS.validation;

import de.corpling.peper.modules.relANNIS.RADAO;
import de.corpling.peper.modules.relANNIS.RAMapper;

import de.corpling.salt.saltFW.SaltProject;

import java.io.File;

/**
 * A sample validator interface for {@link de.corpling.peper.modules.relANNIS.RAExporter}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RAExporterValidator {
	boolean validate();

	boolean validateSaltProject(SaltProject value);
	boolean validateOutputDir(File value);
	boolean validateRaMapper(RAMapper value);
	boolean validateRaDAO(RADAO value);
}
