/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.corpling.peper.modules.relANNIS.validation;

import de.corpling.peper.modules.relANNIS.RADAO;
import de.corpling.peper.modules.relANNIS.RAExporter;

import de.corpling.salt.model.saltCore.SElement;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.corpling.peper.modules.relANNIS.RAMapper}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RAMapperValidator {
	boolean validate();

	boolean validateRaDAO(RADAO value);
	boolean validateCurrTaId(Long value);
	boolean validateRaExporter(RAExporter value);
	boolean validateCoherentComponents(EList<SElement> value);
	boolean validateSubConnectedComponents(EList<SElement> value);
}
