/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.corpling.peper.modules.relANNIS.validation;

import de.corpling.peper.modules.relANNIS.DAOOBJECT;

/**
 * A sample validator interface for {@link de.corpling.peper.modules.relANNIS.TAObject}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TAObjectValidator {
	boolean validate();

	boolean validateTaId(Long value);
	boolean validateTwWriterKey(DAOOBJECT value);
}
