/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.corpling.peper.modules.relANNIS.validation;

import de.corpling.peper.modules.relANNIS.UNIQUE_VALUES;
import de.corpling.peper.modules.relANNIS.UniqueValue;

/**
 * A sample validator interface for {@link java.util.Map.Entry}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UniqueValueEntryValidator {
	boolean validate();

	boolean validateTypedValue(UniqueValue value);
	boolean validateTypedKey(UNIQUE_VALUES value);
}
