DROP USER "relANNIS_flo";
CREATE USER "relANNIS_flo" WITH PASSWORD 'relANNIS';
DROP DATABASE "relANNIS";
CREATE DATABASE "relANNIS" ENCODING = 'UTF8';
ALTER DATABASE "relANNIS" OWNER TO "relANNIS_flo";

\connect "relANNIS"