<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="peper"
    nsURI="www.corpling.de/peper" nsPrefix="peper">
  <eClassifiers xsi:type="ecore:EClass" name="ImExportSet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataSourcePath" eType="#//File"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="formatDefinition" lowerBound="1"
        eType="#//FormatDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="File" instanceClassName="java.io.File"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExportSet" eSuperTypes="#//ImExportSet"/>
  <eClassifiers xsi:type="ecore:EClass" name="ImportSet" eSuperTypes="#//ImExportSet"/>
  <eClassifiers xsi:type="ecore:EClass" name="Importer" eSuperTypes="#//ImExporter">
    <eOperations name="importCorpusStructure"/>
    <eOperations name="importDocument">
      <eParameters name="sDocument" eType="ecore:EClass ../../Salt_version1/model/SaltConcrete.ecore#//SDocument"/>
    </eOperations>
    <eOperations name="close"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inputDir" eType="#//File"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="settingDir" eType="#//File"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Exporter" eSuperTypes="#//ImExporter">
    <eOperations name="export">
      <eParameters name="sCorpus" eType="ecore:EClass ../../Salt_version1/model/SaltConcrete.ecore#//SCorpus"/>
    </eOperations>
    <eOperations name="export">
      <eParameters name="sDocument" eType="ecore:EClass ../../Salt_version1/model/SaltConcrete.ecore#//SDocument"/>
    </eOperations>
    <eOperations name="close"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputDir" eType="#//File"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="settingDir" eType="#//File"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImExporter">
    <eOperations name="isSupported" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="ImExportSet" eType="#//ImExportSet"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedFormats" lowerBound="1"
        upperBound="-1" eType="#//FormatDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="saltProject" eType="#//SaltProject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FormatDefinition">
    <eOperations name="equals" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="otherObject" eType="#//FormatDefinition"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formatName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formatVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formatReference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConvertJob">
    <eOperations name="start"/>
    <eOperations name="addImportSet">
      <eParameters name="importSet" eType="#//ImportSet"/>
    </eOperations>
    <eOperations name="addExportSet">
      <eParameters name="exportSet" eType="#//ExportSet"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importObjects" upperBound="-1"
        eType="#//ImportObject" containment="true" eOpposite="#//ImportObject/convertJob"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exportObjects" upperBound="-1"
        eType="#//ExportObject" containment="true" eOpposite="#//ExportObject/convertJob"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="saltProject" eType="#//SaltProject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="porterEmitter" eType="#//PorterEmitter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImportObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="importer" lowerBound="1"
        eType="#//Importer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importSet" lowerBound="1"
        eType="#//ImportSet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="convertJob" lowerBound="1"
        eType="#//ConvertJob" eOpposite="#//ConvertJob/importObjects"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExportObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exportSet" lowerBound="1"
        eType="#//ExportSet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exporter" lowerBound="1"
        eType="#//Exporter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="convertJob" lowerBound="1"
        eType="#//ConvertJob" eOpposite="#//ConvertJob/exportObjects"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PeperConverter">
    <eOperations name="start"/>
    <eOperations name="addJob">
      <eParameters name="importDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="exportDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="convertJobs" upperBound="-1"
        eType="#//ConvertJob" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PorterEmitter">
    <eOperations name="emitImporter" eType="#//Importer">
      <eParameters name="formatDefinition" eType="#//FormatDefinition"/>
    </eOperations>
    <eOperations name="emitExporter" eType="#//Exporter">
      <eParameters name="formatDefinition" eType="#//FormatDefinition"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="props" eType="#//Properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Properties" instanceClassName="java.util.Properties"/>
  <eClassifiers xsi:type="ecore:EDataType" name="SaltProject" instanceClassName="de.corpling.salt.SaltProject"/>
</ecore:EPackage>
