/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.corpling.peper.validation;

import de.corpling.peper.ExportObject;
import de.corpling.peper.ExportObjects;
import de.corpling.peper.ImportObject;

import de.corpling.peper.PorterEmitter;
import de.corpling.salt.SaltProject;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.corpling.peper.ConvertJob}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConvertJobValidator {
	boolean validate();

	boolean validateImportObjects(EList<ImportObject> value);
	boolean validateExportObjects(EList<ExportObjects> value);
	boolean validateSaltProject(SaltProject value);

	boolean validateSaltProject(String value);

	boolean validatePorterEmitter(PorterEmitter value);
}
