/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.corpling.peper.validation;

import de.corpling.peper.ConvertJob;
import de.corpling.peper.ConvertProject;
import de.corpling.peper.ExportSet;
import de.corpling.peper.Exporter;

/**
 * A sample validator interface for {@link de.corpling.peper.ExportObjects}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ExportObjectsValidator {
	boolean validate();

	boolean validateExportSet(ExportSet value);
	boolean validateExporter(Exporter value);
	boolean validateConvertJob(ConvertJob value);

	boolean validateConvertProject(ConvertProject value);
}
