/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.corpling.peper.validation;


/**
 * A sample validator interface for {@link de.corpling.peper.FormatDefinition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FormatDefinitionValidator {
	boolean validate();

	boolean validateFormatName(String value);
	boolean validateFormatVersion(String value);
	boolean validateFormatReference(String value);
}
