/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.corpling.peper.validation;

import de.corpling.peper.FormatDefinition;

import java.io.File;

/**
 * A sample validator interface for {@link de.corpling.peper.ImExportSet}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ImExportSetValidator {
	boolean validate();

	boolean validateDataSourcePath(File value);
	boolean validateFormatDefinition(FormatDefinition value);
}
