/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.corpling.peper.validation;

import de.corpling.peper.FormatDefinition;

import de.corpling.salt.saltFW.SaltProject;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.corpling.peper.ImExporter}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ImExporterValidator {
	boolean validate();

	boolean validateSupportedFormats(EList<FormatDefinition> value);

	boolean validateName(String value);

	boolean validateSaltProject(SaltProject value);
}
