/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.corpling.peper.validation;

import de.corpling.peper.ConvertJob;
import de.corpling.peper.ConvertProject;
import de.corpling.peper.ImportSet;
import de.corpling.peper.Importer;

/**
 * A sample validator interface for {@link de.corpling.peper.ImportObject}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ImportObjectValidator {
	boolean validate();

	boolean validateImporter(Importer value);
	boolean validateImportSet(ImportSet value);
	boolean validateConvertJob(ConvertJob value);

	boolean validateConvertProject(ConvertProject value);
}
