/*
 * graphANNIS
 * Access the graphANNIS corpora and execute AQL queries with this service. 
 *
 * The version of the OpenAPI document: 0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.corpus_tools.api;

import org.corpus_tools.ApiException;
import org.corpus_tools.annis.api.model.InlineObject1;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthentificationApi
 */
@Ignore
public class AuthentificationApiTest {

    private final AuthentificationApi api = new AuthentificationApi();

    
    /**
     * Create JWT token for credentials of a locally configured account.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void localLoginTest() throws ApiException {
        InlineObject1 inlineObject1 = null;
        String response = api.localLogin(inlineObject1);

        // TODO: test validations
    }
    
}
